### ISSUE TITLE
Block count in special situation wrong

### ISSUE THREAD

**Issue by EvilOlaf** [SBPrime/AsyncWorldEdit#102]
WorldEdit 6.1 (I think 6.0 had the same issue)
AWE 2.2.1
Injector 2.2.0
Spigot 1.8.3

What I do:
- Select a Chunk by using `//chunk`
- Expand chunkwise by using `//expand 16` or `32` or whatever.
- `//expand vert`
- `//regen`
- Depending on how many chunks selecte there should be a million blocks or more but AWE coints just 20 or something like this.

Just a minor issue.

**Comment by SBPrime** [comment]
Regen in WE works like this:
1. Expand selection to full chunks
2. Copy blocks outside the original selection
3. Regen each selected chunk (in the expanded area)
4. Put back the blocks that ware not in the original selection

AWE queues (and counts) only the chunk regen operations + all the blocks that need to be restored after regen.

In your example you selected full chunks and AWE queued regen for only those chunks. WE works like this its not a bug.
