### ISSUE TITLE
Chests Contents Paste Issue

### ISSUE THREAD

**Issue by aikar** [SBPrime/AsyncWorldEdit#105]
Seen affecting Chests but could apply to other TileEntities

When AsyncWorldEdit is used, //paste with chest blocks will not overwrite chest contents if a chest is already in the paste destination.

Example, one chest block selection copied with a chest that has items, then paste onto a block with an existing chest, the dest will not be replaced with the sources chest contents.

Removing dest chest allows source to paste in correctly.

//awe toggle does not fix the issue.

Removing AWE completely fixes issue.

**Comment by JasonHorkles** [comment]
Having this issue again, should I create a new issue or would reopening this one work?

**Comment by SBPrime** [comment]
What version of AWE and WE are you using?

**Comment by JasonHorkles** [comment]
AWE: 3.6.20
WE: 7.1.0;8e55131
(And Minecraft 1.15.2)

**Comment by SBPrime** [comment]
Fix is available in 3.7.0 not in 3.6.20

**Comment by JasonHorkles** [comment]
I'm guessing that's only for premium users rn?
