### ISSUE TITLE
Random blocks/pastes seeming to stay

### ISSUE THREAD

**Issue by TWSSYesterday** [SBPrime/AsyncWorldEdit#110]
http://i.imgur.com/PslTHHv.png - Example, yet if I walk up to it, or to it it disappears, I can't use /j to get to it because it's not a valid block.
Versions of AWE, and WE: http://i.imgur.com/puCpTrA.png
Spigot Version (1.8.7): http://i.imgur.com/qdv4kYV.png
No errors in console.

**Comment by SBPrime** [comment]
This is strange, I'm 99% surre that AWE has nothing to do with it. AWE does not touch how the blocks are send to the player. If this is a "ghost block" then it might be a WE glitch (?). Please try doing the paste witch BlocksHub block change recording and check if something was added removed in the location that the block appears to be.

**Comment by SBPrime** [comment]
No update, closing.
