### ISSUE TITLE
Multiple regen jobs remaining at job queue when done

### ISSUE THREAD

**Issue by EvilOlaf** [SBPrime/AsyncWorldEdit#111]
When cleaning up orphan properties in our survival world multiple regen jobs getting queued at the same time.
That works good so far.

But the jobs were not removed from the job list.
See here: http://www0.xup.in/exec/ximg.php?fid=82083104

AWE 2.2.2

**Comment by EvilOlaf** [comment]
I just noticed https://github.com/SBPrime/AsyncWorldEdit/commit/f78aec97cdd2578603169add1cb2eb287117d0d6

Is this the issue?

**Comment by SBPrime** [comment]
Yes it should fix the reported issue. I did not have the time to test if the reported issue is the same as I fixed a while ago.

**Comment by EvilOlaf** [comment]
Would you release a 2.2.3 or will these changes be introduced in the new premium v3 only?

**Comment by SBPrime** [comment]
As I stated in the AWE discussion: I'm considering pushing critical fixes to the github repository, But I wont push a new release. Of curse you can always compile the code by yourself.

**Comment by EvilOlaf** [comment]
Aight. Thanks

**Comment by SBPrime** [comment]
Fixed in master.
