### ISSUE TITLE
[Question] How to paste schematics using AWE?

### ISSUE THREAD

**Issue by TheCreepySheep** [SBPrime/AsyncWorldEdit#116]
So this is basically a copy of [this issue](https://github.com/SBPrime/AsyncWorldEdit-Premium/issues/9), but I'd really like a bit more explanation on how to do it. I feel like my pasting code is not async because the server freezes on every paste. 
Also my code is now a copy of your and rlf's. Like class declarations or variables etc. [Here] (https://github.com/TheCreepySheep/soap/blob/master/src/main/java/com/creepysheep/mittenAchievements/Generation/GeneratorHouse.java) is my current class that should paste schematics, but I believe it is not using AWE..

Note: Mister rlf was far more advanced than I am.

**Comment by SBPrime** [comment]
1. Do not use **EditSession editSession = new EditSession(BW, -1);**, use the edit session factory.
2. You should look at the blocks placer, performAsAsyncJob (https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/org/primesoft/asyncworldedit/blockPlacer/BlockPlacer.java#L989)

**Comment by PublicGameCoder** [comment]
... I would wish the code is available for other people to read (How to copy/paste to/from save/load schematic.

It is very unclear an people can struggle on this for months. It would be easier to just create a way ourselfs...
