### ISSUE TITLE
[Question] AWE and BlocksHub

### ISSUE THREAD

**Issue by Bloodrayne1995** [SBPrime/AsyncWorldEdit#117]
Hello SBPrime,

you write on AWE description page that BlocksHub can redirect WorldEdit events to LogBlock. But if i go on your BlocksHub description page, it gives me only an opportunity to download BlockHub itself and BlockHub-WorldGuard plugin. 
I installed both, but it wont worked.
Can you help me with the configuration of these two plugins, please?
I'm looking forward to hear from you.

Greetings
Bloodrayne1995
eona-minecraft.de

**Comment by SBPrime** [comment]
Download BlocksHub from here: [https://github.com/SBPrime/BlocksHub/releases/tag/v1.2]
Install: AWE, BlocksHub, Logblock, BlocksHub-Logblock
