### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [SBPrime/AsyncWorldEdit#121]
http://hastebin.com/mokuxizova.avrasm

**Comment by SBPrime** [comment]
Error not caused by AWE.  Used logger plugin is not compatible with AWE.

    ...
    org.bukkit.Location.getBlock(Location.java:87)
    de.diddiz.worldedit.WorldEditLoggingHook$1$1.onBlockChange(WorldEditLoggingHook.java:92)
    com.sk89q.worldedit.extent.logging.AbstractLoggingExtent.setBlock(AbstractLoggingExtent.java:53)
    com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
    com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:67)
    com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78)
    com.sk89q.worldedit.extent.inventory.BlockBagExtent.setBlock(BlockBagExtent.java:111)
    com.sk89q.worldedit.EditSession.setBlock(EditSession.java:507)
    org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.setBlock(ThreadSafeEditSession.java:242)
    ...
