### ISSUE TITLE
Error logging block.

### ISSUE THREAD

**Issue by mat41997** [SBPrime/AsyncWorldEdit#122]
logs
http://hastebin.com/umonikazoq.avrasm

PaperSpigot 1.8.8

Plugins (51): Grenade, FastCraftPlus, LuckyBlock, CustomRecipes, HorseTpWithMe, Simple-AutoSave, AntiJoinBot, ViaVersion, Tablist, SilkChests, Titlebar, AsyncWorldEditInjector, WorldEdit, EggCatcher, Skript, PluginManagerReloaded, SkQuery, RandomTP, Cinema, ProtocolLib, LibsDisguises, NoCheatPlus, ImageMaps, Shopkeepers, HugeItems, WildSkript, BlocksHub, PermissionsEx, StaffChat, Vault, MassiveCore, LogBlock, CreativeGates, HolographicDisplays, WorldGuard, BlocksHub-WorldGuard, ChestCommands, EditableSign, BlocksHub-LogBlock, Essentials, SexyMotd, PreciousStones, AsyncWorldEdit, ColoredTags, EssentialsChat, EssentialsSpawn, Smileychat, AuthMe, LagMonitor, ChangeSkin, MultiWorld

**Comment by SBPrime** [comment]
The appended is not updated to the newest version of LogBlock. I might update it or not as stated on the Spigot Plugin page the dev is on hold.

**Comment by SBPrime** [comment]
BlocksHub has been updated to use the newest version of LogBlock, support for BlocksHub v2 is added.
