### ISSUE TITLE
API: AsyncEditSessionFactory

### ISSUE THREAD

**Issue by Fluxty** [SBPrime/AsyncWorldEdit#129]
This is a **very vague** question I know, but I'm not sure I properly understand how the eventbus works and what value I should give it. I'm guessing it can't be null? Getting an NPE from this:

`AsyncEditSessionFactory asyncFactory = new AsyncEditSessionFactory(awe,null);`

Thanks.

**Comment by SBPrime** [comment]
1. You should not create your own session factory, you should use the edit session factory from WorldEdit getEditSessionFactory
2. You should use the API interfaces

**Comment by Fluxty** [comment]
Thank you SBPrime, I think I'm doing that part right now.. But I still can't seem to get my code to properly generate the schematic when players type the correct command.

http://pastebin.com/TnK9srcH

Would you mind checking over this?
