### ISSUE TITLE
What can I do to speed up the operations?

### ISSUE THREAD

**Issue by hdt80** [SBPrime/AsyncWorldEdit#130]
Hi there, there seems to be huge variance between performing operations and I'm not sure if it's something I'm doing or what else.

For example, running `//cyl stone 200 190` was giving me anywhere between 270bps and 8600bps, with it averaging around 3800bps. 

Running `//cyl stone 1 190` is giving me at most 87bps and as little as 4bps, with it averaging around 8bps. 

What could cause such a massive variance between commands? The world I'm using is the same, I haven't opened or closed any programs, I'm standing in the exact same place (`/tp 0 64 0`), and I'm the person online. All the chunks are generated and void of all blocks (except for those being changed by the command). No mobs are spawning, and the time is locked to 8000 (`/time day -l`). As far as I can tell, all I'm changing is the amount of blocks I'm changing (2.34*10^7 compared to 65280). 

Is there someway to speed up the smaller 65280 block operation to use the 8600bps I was getting before?

**Comment by SBPrime** [comment]
This is most likely due to light updates. To suggest anything else I would need to know what version you are using.

**Comment by hdt80** [comment]
I'm using AsyncWorldEdit `2.3.1` with WorldEdit `6.1.3;7a097ca` (https://github.com/sk89q/WorldEdit/tree/7a097ca56e767a6e912d7e26856be9f5c5eb79c4). 

Thank you for responding quickly and helping me with this, I appreciate it :)

**Comment by SBPrime** [comment]
Ok one thing, please send me your current AWE config.

**Comment by hdt80** [comment]
Sure thing

http://pastebin.com/QH2v1uyi

**Comment by SBPrime** [comment]
interval: 15 <--- set it to 1
default->renderer->blocks: 10000 <-- increase to ~30000 or higher depending on your system.

**Comment by hdt80** [comment]
Looks like that speed up it a lot! Thanks for the help :smile:
