### ISSUE TITLE
Feature Request: Disable the message if server have the last update

### ISSUE THREAD

**Issue by altrisi** [SBPrime/AsyncWorldEdit#133]
I think you can disable the message when the latest version of the plugin is installed, because if you have lots of plugins doing that... It can fill your chat with "You have the latest version" when you join, and without the message the server owner haven't got to read 12489+ messages saying "You have the latest version". The server owner only wants to know if there are a new update. Thanks.

**Comment by TWSSYesterday** [comment]
You can just turn notify update off.

**Comment by altrisi** [comment]
Yes, but if I do that I can't know if there is a new update.

**Comment by TWSSYesterday** [comment]
Follow the resource on Spigot..

**Comment by altrisi** [comment]
I'm doing it, but I don't login in Spigot every day.

**Comment by rautamiekka** [comment]
^ You can activate a watch on a resource, or even a category of, to have email sent to you. Of course, check your settings so that'll happen.

**Comment by SBPrime** [comment]
This was already done ages ago.
