### ISSUE TITLE
I want to uninstall this 

### ISSUE THREAD

**Issue by LoopTurn** [SBPrime/AsyncWorldEdit#137]
I would like to uninstall this but when I try to it doesn't work and I just get this stupid error when I did /cyl bedrock 5 1

23.05 00:43:55 [Server] INFO ... 16 more
23.05 00:43:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
23.05 00:43:55 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
23.05 00:43:55 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
23.05 00:43:55 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
23.05 00:43:55 [Server] INFO at me.frodenkvist.safeedit.PlayerListener.onPlayerCommandPreprocessEvent(PlayerListener.java:104) ~[?:?]
23.05 00:43:55 [Server] INFO at me.frodenkvist.safeedit.SafeEdit.makeCylinder(SafeEdit.java:239) ~[?:?]
23.05 00:43:55 [Server] INFO at me.frodenkvist.safeedit.MakeCylinderRunnable.<init>(MakeCylinderRunnable.java:68) ~[?:?]
23.05 00:43:55 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getPlacementPosition(Lcom/sk89q/worldedit/LocalPlayer;)Lcom/sk89q/worldedit/Vector;
23.05 00:43:55 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
23.05 00:43:55 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
23.05 00:43:55 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
23.05 00:43:55 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
23.05 00:43:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]

**Comment by SBPrime** [comment]
You are using a unsupported version of WorldEdit. Please send the version of AWE + WE that you are using.

**Comment by SBPrime** [comment]
Since there is no reply I'm clossing this.
