### ISSUE TITLE
Tasks will slow down a great deal at random

### ISSUE THREAD

**Issue by agentroop** [SBPrime/AsyncWorldEdit#143]
I've been experiencing this issue for a long time on my server. Most of the time, Async will function just as it should according to configuration. But on occasion it will also slow down for all users on the server for apparently no reason, and I've found no way to recreate the problem.
However, here is the debug report for when a player attempted to a run a command while Async was very slow for everyone: https://pastebin.com/GWMK3Hyg

Please let me know if anything stands out as a bad sign.

Here's my plugin list:
> Plugins (75): Questioner, PerWorldPlugins, TuxTwoLib, PlugMan, BetterChairs, Lockette, VoxelSniper, HeadDrops, SafeArmorStands, PerWorldSpawn, ViaVersion, AsyncWorldEditInjector, ClearAll, CoreProtect, WorldEdit, Skript, MultiInv, AutoMessage, ChatControl, SkQuery, Votifier, ProtocolLib, AdvancedPortals, AsyncWorldEdit, ObsidianBreaker, RedstoneClockDetector, OldPvP, PermissionsEx, skUtilities, mcMMO, GAListener, PerWorldTablist, ServerListPlus, Vault, DailyRewards, OreGeneratorRevolution, ColoredAnvils, MassiveCore, BetterEnderChest, WorldGuard, ASkyBlock, ChestCommands, PlayerVaults, Essentials, PlotMe, CompatNoCheatPlus, Jobs, NoCheatPlus, KitAdder, ColoredTags, OnTime, AdvancedAchievements, React, EssentialsChat, EchoPet, HarmoniCraft, AsyncWorldEdit-PlotMeCore016, EnjinMinecraftPlugin, PlotMe-DefaultGenerator, TrailGUI, Factions, BossShop, EssentialsSpawn, SilkSpawners, Multiverse-Core, Multiverse-Portals, HolographicDisplays, Multiverse-NetherPortals, MultiWorldMoney, Minigames, Towny, Minigames-Regions, CombatTagPlus, MobArena, TownyNameUpdater

**Comment by SBPrime** [comment]
Since 3.x the block placer was rewritten. If this problem is still present let me know.
