### ISSUE TITLE
console error and world edit can't be used

### ISSUE THREAD

**Issue by Castiella** [SBPrime/AsyncWorldEdit#154]
18.01 15:18:54 [Server] INFO Caused by: java.lang.IllegalAccessError: com/sk89q/worldedit/function/operation/Operations$3

In game when you try any world edit command it says 

"Please report this error: java.lang.reflect.InvocationTargetException: null

Happened when i replaced free Aysnc with Premium.

**Comment by Castiella** [comment]
Weird. I restarted and it fixed the issue. Closing.

**Comment by SBPrime** [comment]
1'st thing first: next time please past the full error log  using only 1 line I can't do much.
2'nd: this looks like injector not kicking in. It can happen if you have other plugins that use WE and that load BEFORE AWE injector, or first startup.

**Comment by Castiella** [comment]
Just want to make you aware that I deleted the Injector after a person on your discussion thread told me to delete it. 

Where can i Re-download the injector?

**Comment by SBPrime** [comment]
The injector is automatically recreated after server restart.
