### ISSUE TITLE
Example build

### ISSUE THREAD

**Issue by TWSSYesterday** [SBPrime/AsyncWorldEdit#155]
Would be nice to get an example build.xml that works out of the box, especially for those who paid...

**Comment by TWSSYesterday** [comment]
POM would also be nice if you'd consider it.

**Comment by SBPrime** [comment]
@TWSSYesterday Currently the plugin is not based on maven. I'm planing to move it to maven, but its a low priority. An example build will not be available publicly, but this information is already available to premium users. All you need to do is contact me on spigot.
