### ISSUE TITLE
we can't break anything, however we can build and place blocks.

### ISSUE THREAD

**Issue by MothGirlMusic** [SBPrime/AsyncWorldEdit#163]
using 3.4.11 version of AWE and 6.1.7.3 version of WE. I have essentialsX [antibuild is set up correctly and everything was working fine until installing AWE] 

and when i restarted with AWE in, no one could break anything, however we can build. i had to remove the plugin to get it to allow even the OPs to break anything. what am i missing? after going through the config, there wasn't an option like "allow breaking blocks" or anything. is this supposed to happen? am i supposed to only install the plugin when i need to spawn stuff in?

**Comment by MothGirlMusic** [comment]
Thank you. Through experimentation I found out this plugin was having issues with essentialsX protect. Version 2.0.1. I have removed it in favour of your plugin.

从飞蛾发来

**Comment by SBPrime** [comment]
Still if you could provide the server log I can try to add a workaround to my plugin.
