### ISSUE TITLE
some commands don't work

### ISSUE THREAD

**Issue by fishwasherr** [SBPrime/AsyncWorldEdit#172]
I either am dumb as shit or it is the plugin, but some commands like //tree, /jump and others do not work when AsyncWorldEdit is enabled. How come?

**Comment by SBPrime** [comment]
1. Provide spigot user name
2. Provide the server startup log
3. Provide the server log when you try to execute the command.

**Comment by SBPrime** [comment]
Since there is no response, I'm going to close the issue.
