### ISSUE TITLE
Crash due to //undo

### ISSUE THREAD

**Issue by x1p** [SBPrime/AsyncWorldEdit#175]
Server crash due to //undo. This error exists for a while and is still not fixed apparently.

Error: https://pastebin.com/j7Z4YSK1

This error-log is only a fraction. The real error is about 3375000 lines long. But this does not fit on pastebin.

**Comment by SBPrime** [comment]
If you read the ERROR log you can clearly see that AWE has no access to the disk to store the undo file. Make sure that AWE has write access to plugins/AsyncWorldEdit.

**Comment by x1p** [comment]
I guess so, I can't read java.
If so, I'll have to ask for support from the hosting. Since I can't change that, I am surprised this even has happened. I trust the plugin to take care of this. The plugin makes the directories to store its files in it.

But then again, if so, why not throw an error that its not possible and cancel the undo.

**Comment by x1p** [comment]
The files are made apparently without any problem

**Comment by x1p** [comment]
Asked the hosting provider just to be sure. There is nothing wrong with the file/directory permissions.

**Comment by SBPrime** [comment]
Ok, so does it create the undo files at all? Do the undo work? Or no undo works?

**Comment by x1p** [comment]
Most of the times, it works. Sometimes it does not with a crash as a result

**Comment by SBPrime** [comment]
Ok I would need to see a log that consists of entries starting from the operation that you did up to undo command. I'll keep an eye on this.

**Comment by x1p** [comment]
sure no problem. Only problem: it's almost 500mb with only (the same) error lines. I'll post the top part.
https://file.io/BW7YMr

**Comment by SBPrime** [comment]
Log error fixed in beta-2, undo error fixed in beta-5
