### ISSUE TITLE
Errors, not sure what cause

### ISSUE THREAD

**Issue by x1p** [SBPrime/AsyncWorldEdit#176]
A simple /thru caused a lot of errors. Not sure what is cause and what is result of that. So I'll just give a notice and everybody can have a look.

https://hastebin.com/xenovunoru.sql

using:
Paper-342 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
WorldEdit v7.0.0-SNAPSHOT;3882-79a4121
AsyncWorldEdit v3.6.0-beta-2

**Comment by SBPrime** [comment]
Error caused by plotsquered.

`Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.plotsquared.listener.WEManager`
