### ISSUE TITLE
AsyncWorldEdit-3.6.0-beta-3 Does nothing

### ISSUE THREAD

**Issue by x1p** [SBPrime/AsyncWorldEdit#179]
Async does nothing.
In the chat, it says job done.

https://hastebin.com/makovikizi.md

git-Paper-384 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
AsyncWorldEdit v3.6.0-beta-3
WorldEdit v7.0.0-SNAPSHOT;3917-93a6964

**Comment by x1p** [comment]
Done a test on a test server without plotsquared. No errors, but no blocks either.
```

> [10:53:07 INFO]: Player123 issued server command: /gm 1
> [10:53:12 INFO]: Player123 issued server command: //wand
> [10:53:38 INFO]: Player123 issued server command: //set dirt
> [10:54:33 INFO]: Player123 issued server command: //undo
> [10:54:39 INFO]: Player123 issued server command: //set 1
> [10:54:43 INFO]: Player123 issued server command: //undo
```

**Comment by SBPrime** [comment]
Fixed in beta-4
