### ISSUE TITLE
WorldEdit v7.0.0-SNAPSHOT;3919-93de97d

### ISSUE THREAD

**Issue by x1p** [SBPrime/AsyncWorldEdit#180]
AWE does nothing again with newest WE.
It says: Operation completed, Job [0] setblocks - placing blocks
No blocks are placed

https://hastebin.com/ukelozipow.md

AsyncWorldEdit v3.6.0-beta-4
WorldEdit v7.0.0-SNAPSHOT;3919-93de97d
WorldGuard v7.0.0-SNAPSHOT;1753-0dc5781

**Comment by SBPrime** [comment]
Fixed in beta-5
