### ISSUE TITLE
Brushes Fail

### ISSUE THREAD

**Issue by nexlemav** [SBPrime/AsyncWorldEdit#185]
When trying to use a brush such as "/brush cylinder air 3" nothing happens except fo these console errors linked below

https://pastebin.com/JKWK30hw

**Comment by SBPrime** [comment]
You did not provided information about the installed version.

**Comment by SBPrime** [comment]
And world edit version?

**Comment by nexlemav** [comment]
7.0.0-SNAPSHOT;3919-93de97d

**Comment by SBPrime** [comment]
Fixed in beta 7
