### ISSUE TITLE
InaccessibleObjectException, Unable to make field final jdk.internal.loader.URLClassPath jdk.internal.loader.ClassLoaders$AppClassLoader.ucp accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @3557a3f0 [

### ISSUE THREAD

**Issue by mibby** [SBPrime/AsyncWorldEdit#188]
WorldEdit dev 3937
AsyncWorldEdit dev 3.6.0-beta-9
Java 11.0.1

https://paste.ubuntu.com/p/hPQjYQDMmz/

**Comment by SBPrime** [comment]
AWE does not support java 9+. For reference check here:
https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m

**Comment by mibby** [comment]
@SBPrime Is there any plans in the future to support Java 11? Java 8 should be deprecated with 11 being the new long-term support version.

**Comment by SBPrime** [comment]
You can use Java 9+ as long as you add the parameters from the link that I put in my previous message. 

Regarding your actual question: yes but its at lowest possible priority. Besides as far as I know spigot and worldedit do not officially support 9+.
