### ISSUE TITLE
undo cleanup leaves empty folders

### ISSUE THREAD

**Issue by Bobcat00** [SBPrime/AsyncWorldEdit#189]
AsyncWorldEdit 3.5.4 and CraftBukkit 1.12.2.  After undo cleanup is run, the folder plugins/AsyncWorldEdit/undo has multiple folders named with UUIDs and those folders are empty.  Undo cleanup should delete these empty folders.

**Comment by SBPrime** [comment]
Will be added/changed in future version. Although the directories will be removed only at server restart. This is to prevent potential data lose.

**Comment by Bobcat00** [comment]
Sounds good.  Thanks.

**Comment by SBPrime** [comment]
Done in RC-03
