### ISSUE TITLE
Could not dispatch event: com.sk89q.worldedit.event.extent.EditSessionEvent@11dd5e29

### ISSUE THREAD

**Issue by x1p** [SBPrime/AsyncWorldEdit#193]
https://pastebin.com/GzinjqVq

AsyncWorldEdit v3.6.0-rc-02
WorldEdit v7.0.0-beta-03;b192466
WorldGuard v7.0.0-beta01;01dfebe

**Comment by x1p** [comment]
Could be related to the latest Spigot/Paper which WE has a problem with. Will go back a few versions.

**Comment by SBPrime** [comment]
This is not a bug in AWE, its a problem of plorsquered.
