### ISSUE TITLE
Console told me to send you this.   /forest only did half of the selected area.

### ISSUE THREAD

**Issue by thomasdaley2** [SBPrime/AsyncWorldEdit#200]
> [18:57:06 INFO]: [AsyncWorldEdit] -----------------------------------------------------------------------
> [18:57:06 INFO]: [AsyncWorldEdit] Warning: Class scanner encountered an error while scanning class
> [18:57:06 INFO]: [AsyncWorldEdit] Exception: java.lang.NullPointerException, null
> [18:57:06 INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.scanner.FuzyClassScannerEntry.isMatch(FuzyClassScannerEntry.java:65)
> [18:57:06 INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.scanner.FuzyClassScannerEntry.isMatch(FuzyClassScannerEntry.java:70)
> [18:57:06 INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.scanner.ClassScanner.isBlackList(ClassScanner.java:368)
> [18:57:06 INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.scanner.ClassScanner.isBlackList(ClassScanner.java:321)
> [18:57:06 INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.scanner.ClassScanner.scan(ClassScanner.java:205)
> [18:57:06 INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:128)
> [18:57:06 INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethodEx(Helpers.java:80)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.worldedit.command.RegionCommands.forest(RegionCommands.java:450)
> [18:57:06 INFO]: [AsyncWorldEdit] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [18:57:06 INFO]: [AsyncWorldEdit] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [18:57:06 INFO]: [AsyncWorldEdit] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [18:57:06 INFO]: [AsyncWorldEdit] java.lang.reflect.Method.invoke(Method.java:498)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
> [18:57:06 INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(DispatcherWrapper.java:210)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:275)
> [18:57:06 INFO]: [AsyncWorldEdit] sun.reflect.GeneratedMethodAccessor319.invoke(Unknown Source)
> [18:57:06 INFO]: [AsyncWorldEdit] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [18:57:06 INFO]: [AsyncWorldEdit] java.lang.reflect.Method.invoke(Method.java:498)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:231)
> [18:57:06 INFO]: [AsyncWorldEdit] com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54)
> [18:57:06 INFO]: [AsyncWorldEdit] org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
> [18:57:06 INFO]: [AsyncWorldEdit] org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
> [18:57:06 INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648)
> [18:57:06 INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483)
> [18:57:06 INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [18:57:06 INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [18:57:06 INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
> [18:57:06 INFO]: [AsyncWorldEdit] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [18:57:06 INFO]: [AsyncWorldEdit] java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [18:57:06 INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
> [18:57:06 INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
> [18:57:06 INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
> [18:57:06 INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
> [18:57:06 INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
> [18:57:06 INFO]: [AsyncWorldEdit] java.lang.Thread.run(Thread.java:748)
> [18:57:06 INFO]: [AsyncWorldEdit] Class: class com.sk89q.worldedit.util.TreeGenerator$TreeType
> [18:57:06 INFO]: [AsyncWorldEdit] Object: TREE
> [18:57:06 INFO]: [AsyncWorldEdit] Send this message to the author of the plugin!
> [18:57:06 INFO]: [AsyncWorldEdit] https://github.com/SBPrime/AsyncWorldEdit/issues
> [18:57:06 INFO]: [AsyncWorldEdit] -----------------------------------------------------------------------

**Comment by SBPrime** [comment]
Pleases include the plugin version.

**Comment by thomasdaley2** [comment]
Latest available on Spigot
Spigot 1.13.2
Latest Stable WorldEdit Beta

**Comment by SBPrime** [comment]
You need to include AWE version.

**Comment by SBPrime** [comment]
What version exactly. Technically there are 2 available.

**Comment by SBPrime** [comment]
One last question where did you get the build from?

**Comment by thomasdaley2** [comment]
Good question.... Either GitHub or spigotMc as that's where I get all the plugins. Why? Are there different versions in different places? 

I'm pretty sure I followed one of the links from the Async spigotmc page.

**Comment by thomasdaley2** [comment]
I understand that I am a free user and don't get support. That's not what I'm asking for. The console has this coming up and I would think you'd like to know.

If in the end it helps your plugin improve I'm happy about that as it will benefit me also. 

Async is still working fine, just that message is spamming the console with every action.

**Comment by SBPrime** [comment]
1. The version that you are using was never released as jar nor the source was released for it (the earliest source for 1.13 was in rc not beta). Jars are only available (at the time of writing) only for premium users or if you compile it by yourself. All this means that you are using an illegal copy of the plugin.
2. The error was fixed in one of the RC releases (2 or 3 I can't remember).

**Comment by thomasdaley2** [comment]
How does one steal a free plugin?
