### ISSUE TITLE
rc4 cleanup too frequent 

### ISSUE THREAD

**Issue by SmallSansSerif** [SBPrime/AsyncWorldEdit#207]
Using default config (30 minute intervals) I get frequent cleanups that seem to ignore setting.

https://pastebin.com/dws6j7qG

**Comment by SBPrime** [comment]
Send me the AWE config

**Comment by SBPrime** [comment]
@SmallSansSerif  ok no problem I managed to find the problem. I forgot to remove some debug code. For now you can simply disbale the message (awe->messages->undoCleanup = off)

**Comment by SBPrime** [comment]
Fixed in rc04b
