### ISSUE TITLE
Slow motion operations, error spam and dysfunctional undo

### ISSUE THREAD

**Issue by TheoRetisch1** [SBPrime/AsyncWorldEdit#211]
Hejo!

Changing 170 blocks takes 15 seconds. Larger operations take ages. You can watch how 5 blocks are set at a time.  The same operations with almost the same setup (except for worldedit, craftbook and worldguard) run with FAWE and the default worldedit version almost instant. In addition, the plugin spams the log massively (10000 lines for a small operation). Is this normal, where is my mistake? To avoid any performance problems, I disabled the security checks in the config.

The plugin loads normally: https://pastebin.com/7ycAu6Zc

//Set 0 for 170 the error extends to 17000 lines -> too much for Pastbin. But the operation is performed: https://pastebin.com/71bptrSp
Operations with written 1.13 names result in the same errors.

Undo does not work: https://pastebin.com/ZxFTPE2u

config with disabled checks, same stuff happens with default config: https://pastebin.com/ewMvLJYY

Paper 1.13.2 - 493
Worldguard: 7.0.0-beta01;01dfebe
Worldedit: 7.0.0-beta-04;17f52cb
AsynchronousWorldEdit: 3.6.0-rrc-04b

I've tried it for a while now and I'm not able to set up the plugin to be usable. I am grateful for any help!

**Comment by SBPrime** [comment]
You need to update the worldguard extra flags. The version that you are using does not support AWE.

**Comment by TheoRetisch1** [comment]
Thanks a lot for the quick help, without Worldguardextraflags your plugin runs fine. The performance is great!
