### ISSUE TITLE
Question: Planning regarding the latest dependencies and we builds

### ISSUE THREAD

**Issue by TheoRetisch1** [SBPrime/AsyncWorldEdit#212]
When is an update regarding functionality with the latest Worldguard and Worldedit versions planned?
Since the version you are supporting, stupid destructive API changes have been added again. 

As a result, AWE is not compatible with many plugins. These includes for example: AreaShop, WorldguardExtraFlags, Craftbook and some own creations. Not to mention the bugfixes you miss when using older versions.
I'm originally from FAWE and hoped to save at least the asynchronous part. However, as it appears, the support for current versions is not yet available, even though you are very active. The authors of other plugins will not introduce backwards compatibility. This has already caused massive resistance for FAWE and the plugin was much more popular due to its revolutionary feature. 

So my direct and well-intentioned question: Will you support the current Worldguard and Worldedit API within the next 4 weeks or should I get my team back to normal Worldedit on productive system?  I know the API changes and dependencies suck but what to do xD.

**Comment by SBPrime** [comment]
WorldGuard - This will be added to BlocksHub,
WorldEdit dev - I hasitate about supporting dev builds because of stability, although I'm planing to add an update that should work with the beta-4 and latest dev in next week.

**Comment by TheoRetisch1** [comment]
That sounds fantastic, thanks for the info!
