### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by Rincewind34** [SBPrime/AsyncWorldEdit#216]
Just trying to executing "mvn" in my fork => Fails
Where are the modules for 1.13?

**Comment by SBPrime** [comment]
This is intentional. The code is not going to build out of the box. This is because of copy protection code (witch of curse could not have been released). Also note that releasing any tools/info on how to disable copy protection (or releasing code or jars without it) will be considered software piracy.

**Comment by gp-Airee** [comment]
It's open source code though. Why are you trying to have it both ways of wanting contributions but preventing people from freely obtaining copies? It's obtuse.

**Comment by RossKor** [comment]
Yup, i agree - "you can build it yourself" ... "but we're not going to give you all the assets you need to do it" ... well SBPrime thanks for nothing m8

**Comment by SBPrime** [comment]
@gp-Airee Open source does not mean that you will have everything that you need to compile it. I could provide scans of hand written code and that also would be opensource. I do not expect contributions, I never did. For the entire time the full code was available and easily compilable. If this would change and someone would really get involved I would reconsider. For now if you are a premium user you will get all the instructions (in form of a patch) how to compile the code. Currently if someone would like to contribute he simply can contact me on spigot.

You also asked why. A while ago I decided to abandon minecraft and this plugin, ppl asked me to not do it and they proposed that I should make the plugin premium, so I did. Again time passed and I decided that I will start releasing the free version. But there was a cache: I had to distinguish between those versions. After talking with some colleagues I got to the conclusion that the best option would be to provide only the source without support and without DRM part. 

The source is functionally complete, no parts of the plugin ware removed. If you are a true developer you will be able to comment out the DRM parts within less then 30mins (that includes time needed for testing).

@RossKor Do you know the say: "no free lunch"? If you want to get the latest version you need to spend some time to get it and figure out how to compile the code. The source is feature complete, all assets are available. The part that is not included is the DRM with is not required for the plugin to work.
