### ISSUE TITLE
[Maven] Could not resolve dependencies

### ISSUE THREAD

**Issue by PublicGameCoder** [SBPrime/AsyncWorldEdit#218]
```
Failed to collect dependencies at com.sk89q.worldedit:worldedit-bukkit:jar:[7.0,7.1): No versions available for com.sk89q.worldedit:worldedit-bukkit:jar:[7.0,7.1) within specified range
```
i get the above error when trying to 'Run as Maven build' with parameter 'Package'

This is the POM i use:
```XML
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.unlimitedgamesnetwork</groupId>
  <artifactId>UGNSkyblock</artifactId>
  <version>1.11.2</version>
  <name>UGNSkyblock</name>
<url>http://www.unlimitedgamesnetwork.com/</url>
  <build>
      <plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <configuration>
                  <source>1.7</source>
                  <target>1.7</target>
              </configuration>
          </plugin>
      </plugins>
   </build>
   <repositories>
   	   <!--Spigot Repo-->
       <repository>
           <id>spigot-repo</id>
           <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
       </repository>
       <!--AsyncWorldEdit Repo-->
       <repository>
           <id>github-asyncworldedit-api</id>
           <url>https://raw.githubusercontent.com/SBPrime/AsyncWorldEdit/maven-artifact/</url>            
	   </repository>
   </repositories>
   <dependencies>
    <!--Spigot API-->
    <dependency>
           <groupId>org.spigotmc</groupId>
           <artifactId>spigot-api</artifactId>
           <version>1.9.4-R0.1-SNAPSHOT</version>
           <scope>provided</scope>
    </dependency>
    <!--AsyncWorldEdit API-->
    <dependency>
  		   <groupId>org.primesoft.asyncworldedit</groupId>
  		   <artifactId>AsyncWorldEdit-API</artifactId>
  		   <version>[2.2.0-rc-01, 2.2.0)</version>
    	   <type>jar</type>
	</dependency>
    <!--Json Simple-->
    <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>
</dependencies>
</project>
```

And when I go to the url where it tries to pull the version of. Version 7.0 / 7.1 don't exist at that path.
Path: http://maven.sk89q.com/repo/com/sk89q/worldedit/
So? what do I have to do.
I've done as you've stated at : https://github.com/SBPrime/AsyncWorldEdit/tree/maven-artifact

Full error:
```
[ERROR] Failed to execute goal on project UGNSkyblock: Could not resolve dependencies for project com.unlimitedgamesnetwork:UGNSkyblock:jar:1.11.2: Failed to collect dependencies at org.primesoft.asyncworldedit:AsyncWorldEdit-API:jar:2.2.0-rc-01 -> com.sk89q.worldedit:worldedit-core:jar:[7.0,7.1): No versions available for com.sk89q.worldedit:worldedit-core:jar:[7.0,7.1) within specified range -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by SBPrime** [comment]
This is a dev build of WorldEdit. As far as I know it is not available on the official maven, therefore I use a system path (please check the POM of AWE), I would suggest doing something similar, or searching online for a 3'rd party maven repo (I do not trust those :D )

**Comment by PublicGameCoder** [comment]
I think it is on the official maven page of your plugin.
These are the links I've followed to get there.

- https://www.spigotmc.org/resources/asyncworldedit-premium.9661/ [Look under the header that's called 'API' and click the hyperlink 'Github']
- https://github.com/SBPrime/AsyncWorldEdit-API [Then click the link after the line 'For API Maven go to' and click the link.
- https://github.com/SBPrime/AsyncWorldEdit/tree/maven-artifact [This is where you'll end up and this is where I've got the maven code from (Which is by you the development build and not the release)]

Please update it to the most recent official build so everyone else that wants to use it won't get the same error.

**Comment by SBPrime** [comment]
Ok I think that I understand what you are talking about. I'll push the 05rc API when I'm home. Still it will use the WE jar from system (disk).

**Comment by SBPrime** [comment]
Uploaded the RC05 API. Please check if that fixes the issue.

**Comment by PublicGameCoder** [comment]
Thank you!
I'll check immediately

**Comment by PublicGameCoder** [comment]
Im still getting the same error.
Should the code provided at https://github.com/SBPrime/AsyncWorldEdit/tree/maven-artifact
be changed or not?
It still says:
```
Failed to execute goal on project UGNSkyblock: Could not resolve dependencies for project com.unlimitedgamesnetwork:UGNSkyblock:jar:1.11.2: Failed to collect dependencies at org.primesoft.asyncworldedit:AsyncWorldEdit-API:jar:2.2.0-rc-01 -> com.sk89q.worldedit:worldedit-core:jar:[7.0,7.1): No versions available for com.sk89q.worldedit:worldedit-core:jar:[7.0,7.1) within specified range
```

**Comment by SBPrime** [comment]
Please update the minimum version number for AWE API.

```
<groupId>org.primesoft.asyncworldedit</groupId>
<artifactId>AsyncWorldEdit-API</artifactId>

<version>2.2.0-rc-05</version>
```

**Comment by PublicGameCoder** [comment]
It's working.

But i've got 1 error from changing the version.

Function ``editSession.flushQueue();`` doesn't exist anymore. (editSession = ICancelabeEditSession from the IFuncParamEx<Integer, ICancelabeEditSession, MaxChangedBlocksException>)

Should it be replaced to ``editSession.flushSession();``?

**Comment by SBPrime** [comment]
Yes the WE API changed, and I had to port those changes to my code.
