### ISSUE TITLE
Plugin doesn't load on last version of WorldEdit

### ISSUE THREAD

**Issue by ZombieZone69** [SBPrime/AsyncWorldEdit#220]
Issue : 
When starting the server an error appears on the console and the plugin is completely disabled.

Infos : 
AsyncWorldEdit version -> 3.6.0-rc-05
WorldEdit version -> 7.0.0-SNAPSHOT;4048-5de8e08
Paper version -> git-Paper-527 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Logs :
https://pastebin.com/epuk7DXz

**Comment by SBPrime** [comment]
Only beta releases are supported. With that version they (again) changed lot of core classes of WE. If there is a possibility to support beta-05 and the latest snapshot I will do so, if not it will be available after WorldEdit beta-06 is released.

**Comment by ZombieZone69** [comment]
ok, sorry I did not pay attention to that :/
