### ISSUE TITLE
Java 12 Issue aswell

### ISSUE THREAD

**Issue by BOOM21** [SBPrime/AsyncWorldEdit#225]
Hey,

I have the same issue mentioned in Issue #223, I have checked, that the java.base Module is available in my Java installation, via "java --list-modules", as well as it is listed as a dependency for both the spigot.jar and the AsyncWorldEdit.jar, via "jdeps --list-deps XXX.jar" . Furthermore I have tried to start my spigot instance screen with "java --add-modules ALL-MODULE-PATH ..." or "java --add-modules java.base ..." non the less, I get the same startup ERROR posted in #223 - I would realy appreciade advice to resolve this problem.

Thanks in advance

**Comment by SBPrime** [comment]
Please do not duplicate issues. Add your comment in the other issue.
