### ISSUE TITLE
Could not load 'plugins\AsyncWorldEdit.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by leoncp9** [SBPrime/AsyncWorldEdit#227]
server version: paper spigot 1.13.2 build 624
log
https://pastebin.com/ZUQr9CZS

**Comment by SBPrime** [comment]
Did you read the error? 
**org.bukkit.plugin.UnknownDependencyException: WorldEdit**. You need WorldEdit.

**Comment by leoncp9** [comment]
i have tryed again with wordedit and worldguard 7.0.0
thi is log
https://pastebin.com/qSkweAwk

**Comment by SBPrime** [comment]
You need to use the supported version of WE. Check the release notes. The free version supports WE up to beta-5. For latest version you need the premium one, or you need to compile AWE from source.
