### ISSUE TITLE
Source does not compile

### ISSUE THREAD

**Issue by Tsoccerguy3** [SBPrime/AsyncWorldEdit#229]
C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0>mvn install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'version' contains an expression but should be a constant. @ org.primesoft.asyncworldedit:AsyncWorldEdit_AllInOne:${global.awe.version}, C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0\pom.xml, line 8, column 14
[ERROR] Child module C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0\JarProcessor of C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0\pom.xml does not exist @
[ERROR] Child module C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0\AsyncWorldEdit-spigot_v1_13_R2 of C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0\pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.primesoft.asyncworldedit:AsyncWorldEdit_AllInOne:3.6.0 (C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0\pom.xml) has 2 errors
[ERROR]     Child module C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0\JarProcessor of C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0\pom.xml does not exist
[ERROR]     Child module C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0\AsyncWorldEdit-spigot_v1_13_R2 of C:\Users\ASUS\Dev\AsyncWorldEdit-3.6.0\pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by SBPrime** [comment]
This is intentional. The DRM code was not pushed to github. Full instruction on how to compile the plugin from code is available for premium users.
