### ISSUE TITLE
Player_Head

### ISSUE THREAD

**Issue by M1904** [SBPrime/AsyncWorldEdit#230]
Hello,

i tested awe 3.6.2 with WE RC2 and awe 3.6.3 with WE RC3.
at both, i cannot copy/paste custom player_heads. everytime there's placed an minecraft:player_head (steve).
if i toggle awe, WE do the right job.
can you fix it pls?

**Comment by SBPrime** [comment]
Duplicate:
https://github.com/SBPrime/AsyncWorldEdit-Premium/issues/178
