### ISSUE TITLE
[Critical] Pasting a filled chest over a chest erases all content

### ISSUE THREAD

**Issue by Ferocimo** [SBPrime/AsyncWorldEdit#235]
Hello,

If you copy a full chest, and then paste it right away, the chest will be emptied. However if you destroy the original copy, and then paste the chest, it will correctly be pasted with its content.

This is obviously a huge issue as it renders pasting something on the same location of the copy (typically, for a rollback) basically unusable.

Thank you for looking into this as soon as possible.

**Comment by SBPrime** [comment]
Duplicate https://github.com/SBPrime/AsyncWorldEdit-Premium/issues/178
