### ISSUE TITLE
Schematics laden nicht

### ISSUE THREAD

**Issue by snoozz** [SBPrime/AsyncWorldEdit#236]
Hi! I have the problem that really everything works fine but unfortunately I can not save Schematics because the entire copy command is not. there is always the message: 0 blocks copied and then: Schematic could not be saved. Yours sincerely snoozz

**Comment by SBPrime** [comment]
English

**Comment by SBPrime** [comment]
Please provide:
1. Server startup log,
2. Server log when you do the operation
3. Spigot user name.

**Comment by SBPrime** [comment]
No update, can't reproduce.
