### ISSUE TITLE
Doesnt load properly 

### ISSUE THREAD

**Issue by VerdGehirn** [SBPrime/AsyncWorldEdit#238]
https://pastebin.com/UBYzrAyk

**Comment by bqstnm** [comment]
I have the same result. Using [WorldEdit 7.0.0](https://dev.bukkit.org/projects/worldedit/files/2723275) and AWE 3.6.4

**Comment by cooperisdunn** [comment]
AWE is on version 3.6.6... I sense that you may have downloaded an old version of the plugin from a shady site...

**Comment by SBPrime** [comment]
Duplicate: https://github.com/SBPrime/AsyncWorldEdit/issues/223
Java 12 is not supported.
