### ISSUE TITLE
ASYNC Problem Please help me

### ISSUE THREAD

**Issue by VidarosX** [SBPrime/AsyncWorldEdit#239]
09.07 21:48:45 [Server] INFO CONSOLE: Starting creation of world 'Cidade'...
09.07 21:48:45 [Server] INFO Loading World & Settings - 'Cidade' - Env: NORMAL - Type: NORMAL & generator: AlmostFlatLandsReloaded
09.07 21:48:45 [Server] INFO -------- World Settings For [Cidade] --------
09.07 21:48:45 [Server] INFO Experience Merge Radius: 3.0
09.07 21:48:45 [Server] INFO Mob Spawn Range: 8
09.07 21:48:45 [Server] INFO Cactus Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Cane Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Melon Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Mushroom Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Pumpkin Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Sapling Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Beetroot Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Carrot Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Potato Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Wheat Growth Modifier: 100%
09.07 21:48:45 [Server] INFO NetherWart Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Vine Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Cocoa Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Bamboo Growth Modifier: 100%
09.07 21:48:45 [Server] INFO SweetBerry Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Kelp Growth Modifier: 100%
09.07 21:48:45 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
09.07 21:48:45 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
09.07 21:48:45 [Server] INFO Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
09.07 21:48:45 [Server] INFO Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
09.07 21:48:45 [Server] INFO Max TNT Explosions: 100
09.07 21:48:45 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
09.07 21:48:45 [Server] INFO View Distance: 10
09.07 21:48:45 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
09.07 21:48:45 [Server] INFO Item Merge Radius: 2.5
09.07 21:48:45 [Server] INFO Item Despawn Rate: 6000
09.07 21:48:45 [Server] INFO Arrow Despawn Rate: 1200
09.07 21:48:45 [Server] INFO Zombie Aggressive Towards Villager: true
09.07 21:48:45 [Server] INFO Nerfing mobs spawned from spawners: false
09.07 21:48:49 [Server] INFO GroupManager - INFO - New world detected...
09.07 21:48:49 [Server] INFO GroupManager - INFO - Creating data for: Cidade
09.07 21:48:49 [Server] INFO GroupManager - INFO - Don't forget to configure/mirror this world in config.yml.
09.07 21:48:49 [Server] INFO Preparing start region for dimension 'Cidade'/minecraft:overworld
09.07 21:48:49 [Server] INFO Preparing spawn area: 0%
09.07 21:48:50 [Server] INFO Preparing spawn area: 3%
09.07 21:48:51 [Server] INFO Preparing spawn area: 3%
09.07 21:48:51 [Server] INFO Preparing spawn area: 21%
09.07 21:48:54 [Server] INFO Preparing spawn area: 21%
09.07 21:48:54 [Server] INFO Preparing spawn area: 21%
09.07 21:48:54 [Server] INFO Preparing spawn area: 21%
09.07 21:48:54 [Server] INFO Preparing spawn area: 21%
09.07 21:48:54 [Server] INFO Preparing spawn area: 21%
09.07 21:48:55 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-125 (MC: 1.14.3) ---
09.07 21:48:55 [Server] ERROR The server has not responded for 10 seconds! Creating thread dump
09.07 21:48:55 [Server] ERROR ------------------------------
09.07 21:48:55 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
09.07 21:48:55 [Server] ERROR ------------------------------
09.07 21:48:55 [Server] ERROR Current Thread: Server thread
09.07 21:48:55 [Server] ERROR PID: 23 | Suspended: false | Native: false | State: TIMED_WAITING
09.07 21:48:55 [Server] ERROR Stack:
09.07 21:48:55 [Server] ERROR sun.misc.Unsafe.park(Native Method)
09.07 21:48:55 [Server] ERROR java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
09.07 21:48:55 [Server] ERROR net.minecraft.server.v1_14_R1.MinecraftServer.executeModerately(MinecraftServer.java:973)
09.07 21:48:55 [Server] ERROR net.minecraft.server.v1_14_R1.MinecraftServer.loadSpawn(MinecraftServer.java:597)
09.07 21:48:55 [Server] ERROR org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:1020)
09.07 21:48:55 [Server] ERROR org.bukkit.Bukkit.createWorld(Bukkit.java:492)
09.07 21:48:55 [Server] ERROR org.bukkit.WorldCreator.createWorld(WorldCreator.java:279)
09.07 21:48:55 [Server] ERROR com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
09.07 21:48:55 [Server] ERROR com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:269)
09.07 21:48:55 [Server] ERROR com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
09.07 21:48:55 [Server] ERROR com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
09.07 21:48:55 [Server] ERROR com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
09.07 21:48:55 [Server] ERROR com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
09.07 21:48:55 [Server] ERROR com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:908)
09.07 21:48:55 [Server] ERROR org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
09.07 21:48:55 [Server] ERROR org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
09.07 21:48:55 [Server] ERROR org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
09.07 21:48:55 [Server] ERROR org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701)
09.07 21:48:55 [Server] ERROR net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:459)
09.07 21:48:55 [Server] ERROR net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:421)
09.07 21:48:55 [Server] ERROR net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
09.07 21:48:55 [Server] ERROR net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
09.07 21:48:55 [Server] ERROR java.lang.Thread.run(Thread.java:748)
09.07 21:48:55 [Server] ERROR ------------------------------
09.07 21:48:55 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
09.07 21:48:55 [Server] ERROR ------------------------------
09.07 21:48:57 [Server] INFO Preparing spawn area: 77%
09.07 21:48:57 [Server] INFO Preparing spawn area: 77%
09.07 21:48:57 [Server] INFO Preparing spawn area: 77%
09.07 21:48:57 [Server] INFO Preparing spawn area: 77%
09.07 21:48:57 [Server] INFO Preparing spawn area: 77%
09.07 21:48:57 [Server] INFO Preparing spawn area: 77%
09.07 21:48:57 [Server] INFO Loaded 441 spawn chunks for world Cidade
09.07 21:48:57 [Server] INFO Time elapsed: 8288 ms
09.07 21:48:57 [Server] INFO Default configuration file written: /plugins/WorldGuard/worlds/Cidade/config.yml
09.07 21:48:57 [Server] INFO Default configuration file written: /plugins/WorldGuard/worlds/Cidade/blacklist.txt
09.07 21:48:57 [Server] INFO (Cidade) TNT ignition is PERMITTED.
09.07 21:48:57 [Server] INFO (Cidade) Lighters are PERMITTED.
09.07 21:48:57 [Server] INFO (Cidade) Lava fire is PERMITTED.
09.07 21:48:57 [Server] INFO (Cidade) Fire spread is UNRESTRICTED.
09.07 21:48:57 [Server] INFO Loaded configuration for world 'Cidade'
09.07 21:48:57 [Server] INFO CONSOLE: Complete!
09.07 21:48:57 [Server] WARN Can't keep up! Is the server overloaded? Running 8356ms or 167 ticks behind
09.07 21:49:04 [Server] INFO TPS low (16.58). Will attempt to freeze some mobs...
09.07 21:49:04 [Server] INFO 3 mobs have been frozen in 17ms (4/62 now frozen).

**Comment by SBPrime** [comment]
1. The provided stack contains no references to AWE,
2. You did not provide the version of WE, AWE, Spigot,
3. You did not provide the full server startup log,
4. You did not provide your spigot user name.
