### ISSUE TITLE
Pasting schematics

### ISSUE THREAD

**Issue by Lammendam** [SBPrime/AsyncWorldEdit#241]
I have very big schematic (20 million blocks). I have loaded it to server memory and now i execute //paste. Response:
`Job [0] paste - placing blocks`
few minutes ago AWE responses
`Server is running low on memory. Queue locked.`
but with tools i checked that server works fine, TPS is 20 and memory is in default stage. No lags i experience. Only when i load it to memory.
Nothing else i'm not see from plugin with this paste job. Console empty. Server is not crash.
Looks like, schematic isn't pasting on the map.
What i have to do to fix this?

When i try to cancel this job i got this error in console: https://pastebin.com/X6nx5Ukq

AWE version 3.6.4
WE version 7.0.1 build 4521

**Comment by SBPrime** [comment]
This is a problem of your setup, not a bug in the plugin. Your server is running out of ram. Technical support is provided only for premium users.

**Comment by Lammendam** [comment]
You think this is normal that plugin pasting schematic by 1 block once a few minutes? Ram usage during pasting: 700-800 MB using of 3641 MB... What kind of memory shortage can there be? I said: TPS is 20.0. Ram usage is low... there is some kind of mistake, and certainly not with my setup.
Anyway, thank you for your comment. Have a nice day.

**Comment by SBPrime** [comment]
check the plugin config part responsible for memory limits. The ram is used by WE for undos and by AWE for queuing each block. 3G of free ram is not enough to paste 20M blocks.
https://github.com/SBPrime/AsyncWorldEdit/wiki#how-many-blocks-can-i-queue
