### ISSUE TITLE
[Question] How to paste schematics using AWE 3.5.4?

### ISSUE THREAD

**Issue by CKATEPTb** [SBPrime/AsyncWorldEdit#244]
Example [1.12.2](https://gitlab.com/bending/bendingarenamanager/tree/master/src/main/java/ru/ckateptb/bendingarenamanager/schematics) [1.13.2 1.14.2](https://gitlab.com/bending/bendingarenamanager/tree/1.13+/src/main/java/ru/ckateptb/bendingarenamanager/schematics)

> # Thing that you will need globally:
> ```
> IAsyncWorldEdit aweAPI = (IAsyncWorldEdit)Bukkit.getServer().getPluginManager().getPlugin("AsyncWorldEdit");
> IAsyncEditSessionFactory esFactory = (IAsyncEditSessionFactory)WorldEdit.getInstance().getEditSessionFactory();
> IBlockPlacer blockPlacer = aweAPI.getBlockPlacer();
> IPlayerManager playerManager = aweAPI.getPlayerManager();
> ```
> 
> # Now couple of options to choose from:
> ## 1. If you have `Player p` that is executing the command:
> ```
> IPlayerEntry awePlayer = playerManager.getPlayer(p.getUniqueId());
> ```
> 
> ## 2. If you are executing this from console:
> ```
> IPlayerEntry awePlayer = playerManager.getConsolePlayer();
> ```
> 
> ## 3. If you want to execute this as your plugin (not tied to console and to a player):
> ```
> UUID myUUID = UUID.randomUUID(); //Or a constant one if you prefer
> String myName= "your_plugin_name";
> IPermissionGroup perms = createCustomPermission(); // You need to implement this or use createFakePlayer without the perms parameter
> IPlayerEntry awePlayer = playerManager.createFakePlayer(myName, myUUID, perms);
> ```
> 
> # An example how to perform any WE operation in async:
> ```
> World world = ...
> int maxBlocks = ... // can be -1
> BlockBab bb = ... // can be null
> IThreadSafeEditSession es = 	esFactory.getThreadSafeEditSession(world, maxBlocks, bb, awePlayer);
> 
> blockPlacer.performAsAsyncJob(es, awePlayer, "The name of your job", new IFuncParamEx<Integer, ICancelabeEditSession, MaxChangedBlocksException>() {
>   @Override
>   public Integer execute(ICancelabeEditSession editSession) throws MaxChangedBlocksException
>   {
>     // perform any operations that you need using the editSession
>     return ...
>   }
> });
> ```
> 
> # Links that might be useful:
> https://gist.github.com/aikar/c7d41a3ccdb139aeb5e13644cb079689
> https://gist.github.com/Postremus/3087b9905a92af23afdd
> https://www.programcreek.com/java-api-examples/?code=rlf/uSkyBlock/uSkyBlock-master/uSkyBlock-AWE330/src/main/java/us/talabrek/ultimateskyblock/handler/asyncworldedit/AWE330Adaptor.java
> [SBPrime/AsyncWorldEdit-Premium#9](https://github.com/SBPrime/AsyncWorldEdit-Premium/issues/9)
> https://pastebin.com/bsfxmSRu

**Comment by SBPrime** [comment]
You are using old WE API, please consult WE documentation on how to do it properly. After that I can help you make it async.

**Comment by CKATEPTb** [comment]
```
public class AWESchematicPlacer implements ISchematicPlacer {
    IAsyncWorldEdit awe;
    FileConfiguration config;

    public AWESchematicPlacer(Plugin plugin) {
        awe = (IAsyncWorldEdit) plugin;
        config = BendingArenaManager.arenas.getConfig();
    }

    public EditSession getEditSession(BukkitWorld world) {
        IAsyncEditSessionFactory sessionFactory = (IAsyncEditSessionFactory) worldEdit.getEditSessionFactory();
        return (EditSession) sessionFactory.getThreadSafeEditSession(world, Integer.MAX_VALUE, null, awe.getPlayerManager().getUnknownPlayer());
    }

    @Override
    public File getSchematic(String name) {
        return new File(BendingArenaManager.plugin.getDataFolder() + sep + "AsyncWorldEdit" + sep + "schematics" + sep + name + ".schematic");
    }

    @Override
    public boolean deleteSchematic(String name) {
        File file = getSchematic(name);
        if (file.exists())
            return file.delete();
        return true;
    }

    @Override
    public boolean loadSchematic(String arena, Location loc) {
        try {
            File schematic = getSchematic(arena);
            final CuboidClipboard cc = SchematicFormat.MCEDIT.load(schematic);
            EditSession es = getEditSession(new BukkitWorld(loc.getWorld()));
            cc.paste(es, BukkitUtil.toVector(loc), false);
            return true;
        } catch (MaxChangedBlocksException | IOException | DataException e) {
            e.printStackTrace();
        }
        return false;
    }

    @Override
    public boolean saveSchematic(String arena, Selection sel) {
        try {
            BukkitWorld world = new BukkitWorld(sel.getWorld());
            Vector pos1 = sel.getNativeMinimumPoint().toBlockPoint();
            Vector pos2 = sel.getNativeMaximumPoint().toBlockPoint().subtract(pos1).add(new Vector(1, 1, 1));
            CuboidClipboard clipboard = new CuboidClipboard(pos2, pos1, new Vector(0, 0, 0));
            EditSession editSession = getEditSession(world);
            clipboard.copy(editSession);
            File file = getSchematic(arena);
            if (file.exists())
                file.delete();
            if (!file.getParentFile().exists())
                file.getParentFile().mkdirs();
            if (!file.exists())
                if (file.createNewFile()) {
                    SchematicFormat.MCEDIT.save(clipboard, file);
                    return true;
                }
        } catch (IOException | DataException e) {
            e.printStackTrace();
        }
        return false;
    }
}
```

**Comment by CKATEPTb** [comment]
https://gitlab.com/bending/bendingarenamanager

**Comment by SBPrime** [comment]
Why didint you use the Operations and visitors API?

**Comment by CKATEPTb** [comment]
Can you give me an example? Or done in my code so that I suffer less. Disc: CKATEPTb#2126

**Comment by SBPrime** [comment]
The code that you have will only work for actual block placing. Not for preparation. Witch part of the code (method names) are you trying to async? do you need to wait for the operations to finish?

**Comment by CKATEPTb** [comment]
I want to make fully async save, load and paste schematic with use asyncworldedit.

**Comment by SBPrime** [comment]
Ok I'll prepare a stub method for you, I need to knwo if you need to wait for the pasting/loading/saving to finish?

**Comment by CKATEPTb** [comment]
Yes

**Comment by SBPrime** [comment]
I'll prepare a some example code for you.

**Comment by CKATEPTb** [comment]
Well thank you

**Comment by CKATEPTb** [comment]
up

**Comment by SBPrime** [comment]
Sorry for the last week i was on vacation.
You can refer what is writtrn in here:

https://github.com/SBPrime/AsyncWorldEdit/issues/247

**Comment by CKATEPTb** [comment]
![image](https://user-images.githubusercontent.com/33106029/62449309-90806880-b772-11e9-980f-b8ebaec15b77.png)
I sent you the source, it shows that the process is trying to be performed asynchronously, moreover, it is done asynchronously, but the TPS is slipping through. If you embed the same schematic with using command, TPS is not squandered.

**Comment by SBPrime** [comment]
Try using blocks placer perform as async operation for each operation that you have implemented.

**Comment by CKATEPTb** [comment]
as I understand it, I won’t see an example

**Comment by SBPrime** [comment]
I told you that Im on vacations i cant prepare an example right now.

**Comment by CKATEPTb** [comment]
Oh, sorry, I thought your vacation was over, maybe I lost something during the transfer. Thank.

**Comment by SBPrime** [comment]
# Thing that you will need globally:

```
IAsyncWorldEdit aweAPI = (IAsyncWorldEdit)Bukkit.getServer().getPluginManager().getPlugin("AsyncWorldEdit");
IAsyncEditSessionFactory esFactory = (IAsyncEditSessionFactory)WorldEdit.getInstance().getEditSessionFactory();
IBlockPlacer blockPlacer = aweAPI.getBlockPlacer();
IPlayerManager playerManager = aweAPI.getPlayerManager();
```

# Now couple of options to choose from:
## 1. If you have `Player p` that is executing the command:
```
IPlayerEntry awePlayer = playerManager.getPlayer(p.getUniqueId());
```
## 2. If you are executing this from console:
```
IPlayerEntry awePlayer = playerManager.getConsolePlayer();
```

## 3. If you want to execute this as your plugin (not tied to console and to a player):
```
UUID myUUID = UUID.randomUUID(); //Or a constant one if you prefer
String myName= "your_plugin_name";
IPermissionGroup perms = createCustomPermission(); // You need to implement this or use createFakePlayer without the perms parameter
IPlayerEntry awePlayer = playerManager.createFakePlayer(myName, myUUID, perms);
```

# An example how to perform any WE operation in async:
```
World world = ...
int maxBlocks = ... // can be -1
BlockBab bb = ... // can be null
IThreadSafeEditSession es = 	esFactory.getThreadSafeEditSession(world, maxBlocks, bb, awePlayer);

blockPlacer.performAsAsyncJob(es, awePlayer, "The name of your job", new IFuncParamEx<Integer, ICancelabeEditSession, MaxChangedBlocksException>() {
  @Override
  public Integer execute(ICancelabeEditSession editSession) throws MaxChangedBlocksException
  {
    // perform any operations that you need using the editSession
    return ...
  }
});

# Links that might be useful:
https://gist.github.com/aikar/c7d41a3ccdb139aeb5e13644cb079689
https://gist.github.com/Postremus/3087b9905a92af23afdd
https://www.programcreek.com/java-api-examples/?code=rlf/uSkyBlock/uSkyBlock-master/uSkyBlock-AWE330/src/main/java/us/talabrek/ultimateskyblock/handler/asyncworldedit/AWE330Adaptor.java
https://github.com/SBPrime/AsyncWorldEdit-Premium/issues/9
https://pastebin.com/bsfxmSRu

**Comment by SBPrime** [comment]
I assume that since you closed the issue the code helped?

**Comment by CKATEPTb** [comment]
yes, thanks.

> I assume that since you closed the issue the code helped?
