### ISSUE TITLE
Progress in action bar not working no matter what

### ISSUE THREAD

**Issue by lucasboss45** [SBPrime/AsyncWorldEdit#248]
So I've tried using every single API and none of them are working I can't seem to get anything to show up in the actionbar while using AWE even with using the right commands to enable these, and enabling them in the config. Also what's up with the fact that it's telling me that there's a new version available (3.6.9) and when I check the github release page the latest release is 3.6.4?

**Comment by SBPrime** [comment]
The 3.6.9 is the latest premium release, the 3.6.4 is the latest free release. The free version and the premium version share the same code therefore the free one checks against the premium version not the free version. This is intentional, I consider this as an advertisement.

Action bar: DId you enable the AB bridge in AWE plugins?

**Comment by lucasboss45** [comment]
If you're talking about the progress-bar setting in the AWE config, yes it is enabled.

**Comment by SBPrime** [comment]
If you installed AWE correctly it should create  couple of files in the awe configuration directory. One of those is the bridge plugin plugin. So no I'm not talking about the configuration.

**Comment by alexvermaning0** [comment]
its not working for me
its enabled in config
![image](https://user-images.githubusercontent.com/17603899/64490615-0179db00-d25f-11e9-8b36-95a7363792d8.png)

**Comment by alexvermaning0** [comment]
i saw that there was an option that was set to show only if there are 100 blocks in queue
for some reason it just doesen't reach the 100 queue the bps is 1200
the server has 8GB ram

**Comment by SBPrime** [comment]
You can try awe speed 1 and then perform a larger set. You should be happy that it never reaches 100 blocks ;)

**Comment by alexvermaning0** [comment]
> You can try awe speed 1 and then perform a larger set. You should be happy that it never reaches 100 blocks ;)
in the default config. it wil not show the barapi thing unless its above the 100 blocks in queue.
i turned that down to 1 and its still not working

**Comment by SBPrime** [comment]
Did you instal action bar api plugin? Please send the server startup log.

**Comment by alexvermaning0** [comment]
https://pastebin.com/iQqAH1Yc

**Comment by SBPrime** [comment]
```[AsyncWorldEdit]: Unable to load plugin: AsyncWorldEdit-ActionBarAPI.jar, check dependencies.```
You are using an unsupported version of actionbarapi. For further diagnosis I would need to have the jar of ActionBarAPI that you are using.

**Comment by SBPrime** [comment]
I'm using the exact same version and it works without any issues. Where do you have the  AsyncWorldEdit-ActionBarAPI.jar?

**Comment by alexvermaning0** [comment]
i copyed it to the plugins folder so its in both folders

**Comment by alexvermaning0** [comment]
i made an test server with 2 GB ram

MC version 1.14.4
Plugins: AsyncWorldedit-3.6.4.jar
Asyncworldedit-ActionbarAPI.jar
Worldedit-bukkit-8.0.1.jar

AWE config: default (changed the progress bar minimum to 1)

**Comment by SBPrime** [comment]
Don't copy the bridge plugins to plugins, keep those in the awe plugins.

**Comment by alexvermaning0** [comment]
i think adding the plugin to the plugins folder broke it and when i removed it i still diden't see it unless i lower the speed of blockplacing even tho i set it to a minimum of 1 block.
