### ISSUE TITLE
//undo completely unusable

### ISSUE THREAD

**Issue by TruVanillaYami** [SBPrime/AsyncWorldEdit#251]
Hey, the title is pretty much it.
When using WorldEdit, the //undo command either partially works, or never works. It's only when using AsyncWorldEdit though, since completely removing the plugin made it work normally again. AWE also gets stuck with the task, making me have to use /awe purge to remove all of the tasks anytime I accidentally use it out of habit. Help?
(Sorry, I'm new to GitHub...)

**Comment by SBPrime** [comment]
You need to send the server logs (startup, for the command that you want to undo and undo). Also your spigot user.

**Comment by SBPrime** [comment]
No response.
