### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by BearLeonLight** [SBPrime/AsyncWorldEdit#252]
[error.txt](https://github.com/SBPrime/AsyncWorldEdit/files/3560520/error.txt)

**Comment by SBPrime** [comment]
MIssing:
1. Server startup log
2. AWE, WE version
3. Spigot user name.

**Comment by BearLeonLight** [comment]
AWE:3.6.10.jar
WE:7.0.1;61bc012
Spigot user name:BearLeonLight
LOG:https://docs.google.com/document/d/1_D1TEHNKwyUigu4T3f1CXM6X2vJEudEXfsEtNxpbK-M/edit?usp=sharing

**Comment by SBPrime** [comment]
1. Install blocks hub,
2. Disable coreprotect WE integration
3. Enable BH coreprotect integration
4. Enable AWE BH integration.
