### ISSUE TITLE
All world edit commands arnt working

### ISSUE THREAD

**Issue by ItzAnimal** [SBPrime/AsyncWorldEdit#254]
So I run a 1.12 spigot server, meaning I have to download 3.5.4? (Or the correct version, I'm going with memory) So I've installed it, the folder appears in the plugins folder and its green in the plugins list (on server) but when ever I tired to run a copy command or a paste, or even anything world edit related, I get an error alike this one:

> [Fri, 13. Sep 2019 08:15:18 UTC INFO] ItzAnimal issued server command: //copy

> [Fri, 13. Sep 2019 08:15:18 UTC ERROR] [WorldEdit] Could not dispatch event:
> com.sk89q.worldedit.event.platform.CommandEvent@7b7e203e to handler 
> EventHandler{priority=NORMAL}

expect it would be different around the "@7b7e203e" for each command.
I'll include a picture of the plugins list in the attached files.
![2019-09-13_18 18 11](https://user-images.githubusercontent.com/55274421/64847720-fb1aa300-d652-11e9-9c2f-dafc0ec37ec3.png)

If you can tell me whats wrong or what plugin is possibly incompatible, that would be a major help! Thanks <3

~Kind reguards ItzAnimal / Jeremy

**Comment by ItzAnimal** [comment]
Please don't worry, I think I may have fixed the issue! but I think the server may be just low on ram, I realized it didn't have the injector

**Comment by Ghost8797** [comment]
How do you get the injector?

**Comment by ItzAnimal** [comment]
I installed blocksHub 3.1.0

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SBPrime** [comment]
Use AWE 3.5.4 and WE 6.1.7.3, make sure to remove the injector and do a full restart. 
Full support is available for premium users thru spigot PM,
