### ISSUE TITLE
Blocks Queued. Placing speed 0.00 bps, infinitys left

### ISSUE THREAD

**Issue by techdean** [SBPrime/AsyncWorldEdit#257]
It's not pasting it.. the speed never changes from 0.00 and it started growing until it reached infinitys left.

**Comment by techdean** [comment]
This fixed it for me:
https://pastebin.com/yUyeXnGK

**Comment by SBPrime** [comment]
Please provide:
1. Spigot user name
2. Server startup log
3. Log for the paste operation

**Comment by SBPrime** [comment]
No response.
