### ISSUE TITLE
Flipping stairs doesn't work as expected

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/AsyncWorldEdit#259]
- copied the first 3*3 stair area
- //flip
- pasted the thing

The problem is with corner stairs (outer and inner)

**Comment by Tsoccerguy3** [comment]
The bug is in Worldedit https://dev.enginehub.org/youtrack/issue/WORLDEDIT-4004
I reported it . I also texted Me4502 about it On Enginehub Discord . If you search for flip stairs on Discord you'll find the conversation and the reson why it happens

**Comment by Tsoccerguy3** [comment]
is this issue now fixed? I see it still open in the Worldedit issue tracker

**Comment by SBPrime** [comment]
If its a we error it should be fixed by the we team, it should not be here

**Comment by Tsoccerguy3** [comment]
Issue has been fixed https://github.com/EngineHub/WorldEdit/pull/526
testing before merging into the Master branch . It is a good idea to support the Master branch. Bugs get squashed quickly and is more reliable than the beta's
