### ISSUE TITLE
Average Block Placing Speed for better Left Time - Add configuration option

### ISSUE THREAD

**Issue by strongworldDevel** [SBPrime/AsyncWorldEdit#265]
Hey,

it would be great to average the BPS for the last, idk, Minute, to get a more preceise "time left" value.

Best Regards

**Comment by SBPrime** [comment]
Actually the BPS is calculated in a bit more fancy way then using a simple AVG. I use something called running average that uses 5 data points. I'll add an option to the configuration so you will be able to choose how many samples to include.

**Comment by strongworldDevel** [comment]
Thanks man, that's the solution i hoped for :)

**Comment by SBPrime** [comment]
Added config option in 3.6.12
