### ISSUE TITLE
//set command error

### ISSUE THREAD

**Issue by obzidi4n** [SBPrime/AsyncWorldEdit#267]
Selecting a Worldedit region of any size and attempting to //set to any material  (in this case, //set stone) is spawning a java.lang.IndexOutOfBoundsException ..    

Running AsyncWorldEdit 3.6.11 on Paper 1.14 build #255, and WorldEdit 7.0.1.

Console copied here:
[console.txt](https://github.com/SBPrime/AsyncWorldEdit/files/3801674/console.txt)

**Comment by SBPrime** [comment]
Looks like java 12, it is not supported. If this is not the case you need to update to 3.6.13, enable debug mode and manually configure the black list in awe config.
