### ISSUE TITLE
AWE not working

### ISSUE THREAD

**Issue by masterstreamer** [SBPrime/AsyncWorldEdit#272]
AWE is enabled, /awe help works and /awe toggle shows activated or deactivated. But the blocks won't be queued.

Full server startup log: https://pastebin.com/raEa76YG

Spigot version: git-Spigot-56f8471-7554e08 (MC: 1.14.4) Implementing API version 1.14.4-R0.1-SNAPSHOT

AWE-Version: 3.6.11

Version WorldEdit: 7.0.1-rc1;edb2e91

**Comment by SBPrime** [comment]
Java 12 is not supported, at least not yet.

**Comment by masterstreamer** [comment]
@SBPrime Oh, ok. When is it planned to support it?

**Comment by SBPrime** [comment]
In near future but its not high on priority simply because I heavily relay on reflection.

**Comment by John-H-Smith** [comment]
@SBPrime Any news on that?
