### ISSUE TITLE
AsyncWorldEdit incorrectly reports update available.

### ISSUE THREAD

**Issue by Magicrafter13** [SBPrime/AsyncWorldEdit#276]
I get the message saying "You have an old version of the plugin. Your version: 3.6.11, available: 3.6.15-BETA-01" (it said 3.6.14 last time I think).
However, when going to the releases tab, the version at the top is the same, being 3.6.11.

**Comment by SBPrime** [comment]
This is intentional. The plugin informs you about all updates for premium version no mater if you are using the premium or free version.
