### ISSUE TITLE
IAsyncWorldEdit#getBlockPlacer is null? :o

### ISSUE THREAD

**Issue by PaulusDevelopus** [SBPrime/AsyncWorldEdit#284]
hello,

`private IAsyncWorldEdit getAwe() {
        return (IAsyncWorldEdit) Bukkit.getPluginManager().getPlugin("AsyncWorldEdit");
    }`

`        Validate.notNull(getAwe().getBlockPlacer(), "BlockPlacer cannot be null!");
`

Is it normal, that i'm getting the output from the Validate#notNull check? :/

plugin.yml depend contains AsyncWorldEdit and WorldEdit
Serverversion is 1.15.1

**Comment by SBPrime** [comment]
Aparently you are making the call to soon. The block placer is initialized/available after the server is ready. Also make sure that the plugin initializes correctly (check the startup log).

**Comment by PaulusDevelopus** [comment]
Hello,

the plugin initialized not correclty : https://hatebin.com/imbqbsdqmh

**Comment by SBPrime** [comment]
```[17:48:29] [Server thread/INFO]: [AsyncWorldEdit] * >>>> Please make sure that you are using a supported version of world edit <<<<```

Please refer to the release notes, and install the proper version of WE.
