### ISSUE TITLE
Unknown property 

### ISSUE THREAD

**Issue by llronaldoll** [SBPrime/AsyncWorldEdit#285]
[04:32:54] [Craft Scheduler Thread - 20/WARN]: Unknown property east for block minecraft:cobblestone_wall

I am receiving this spam on the console by executing some commands like // undo

**Comment by SBPrime** [comment]
This error report is completely useless. You need to provide more information. A good start would be the server startup log and what you are trying to undo.

**Comment by SBPrime** [comment]
No response closing.
