### ISSUE TITLE
Navigation Wand issue

### ISSUE THREAD

**Issue by Emivg** [SBPrime/AsyncWorldEdit#286]
Hello!

When I use my staff mode plugin and I click my compass it says im using the navigationWand

http://prntscr.com/quk5xp

I already changed that to a clock in the worldedit config

`navigation-wand:
    item: 'minecraft:clock'
    max-distance: 100`

I contacted WE support and they told me its a asyncworldedit problem

Im using last nopremium version for 1.15.2 paper server

Regards

**Comment by SBPrime** [comment]
I tried to reproduce this multiple times. Unfortunately I'm unable to reproduce. You need to provide more details.

**Comment by SBPrime** [comment]
No response closing.
