### ISSUE TITLE
[Question] "Done" Message

### ISSUE THREAD

**Issue by x1p** [SBPrime/AsyncWorldEdit#287]
Due to the large numbers of messages like:
```
You have 123456 out of 9999999 blocks (7.00%) queued.
Placing speed: 2000bps, 60.00s left.
```
I raised the talk values.

Problem: most of the time, the "done" message does not appear.
The last line is something like: ."speed ...., 5s left"

Wish: I would like to done message to appear always.

Question: how can I make sure the "done" message always appears?

**Comment by SBPrime** [comment]
Done in 3.6.19
