### ISSUE TITLE
Spigot Installation guide is not updated

### ISSUE THREAD

**Issue by mkcoldwolf** [SBPrime/AsyncWorldEdit#288]
![image](https://user-images.githubusercontent.com/32544898/74371071-24fb1000-4e13-11ea-8e52-2c08d576af1a.png)
v3.5.4 or below is used for WorldEdit 6.1.9, the guide is not updated and pointing me to download a incompatible version of AsyncWorldEdit

**Comment by SBPrime** [comment]
Installation instruction was updated
