### ISSUE TITLE
Unable to //set

### ISSUE THREAD

**Issue by metalshark** [SBPrime/AsyncWorldEdit#289]
Twice yesterday the `//set` command wouldn't work (am on the latest version 7.1.0 of WorldEdit and 3.6.18 of AsyncWorldEdit Premium). Both excerpts from the console logs can be found here: https://paste.gg/p/metalshark/7f84cdb9c20e430c8badb31a0d308197

**Comment by SBPrime** [comment]
Sorry for the late answer, I focus on the issues reported on spigot not on github. You should set log level to debug and do a small edit. Then the log should show what is the problem.

**Comment by wildmaster84** [comment]
Havign the same issue, i sried to edit a 1x1 block abd this is whats printed:

at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:188) ~[?:?]

This is also a bug in older versions and the only way to fix it is to remove AsyncWorldEdit, i tried reinstalling it and worldedit but had no luck.

**Comment by SBPrime** [comment]
Without full server startup log I won't be able to help.

**Comment by wildmaster84** [comment]
[latest.log](https://github.com/SBPrime/AsyncWorldEdit/files/4358048/latest.log)
theres the hole log

**Comment by SBPrime** [comment]
@wildmaster84 Java 12 is not supported.

**Comment by wildmaster84** [comment]
im not using java 12 im using java 14 ._.

**Comment by SBPrime** [comment]
Only java up to 11 is supported,
Since this is not a problem with the plugin but user error, no further support will be provided. Full support is available for premium users.
