### ISSUE TITLE
Watchdog trips when performing large area //regen commands

### ISSUE THREAD

**Issue by metalshark** [SBPrime/AsyncWorldEdit#290]
This plugin manages asynchronous operations well for everything I've used so far, apart from `//regen` (am on the latest version 7.1.0 of WorldEdit and 3.6.18 of AsyncWorldEdit Premium).

If I regenerate a large enough area the server crashes due to the watchdog timing out.

Here is an example with a smaller area:
https://paste.gg/p/metalshark/038b267a0054470296222daf1cb5c61e

**Comment by SBPrime** [comment]
Fixed in 3.6.19
