### ISSUE TITLE
Brushes aren't working

### ISSUE THREAD

**Issue by metalshark** [SBPrime/AsyncWorldEdit#292]
Any attempt to use a brush does not work and results in errors to the console:
https://paste.gg/p/metalshark/7697d129fdc44732855b0b9c79239253

Am on the latest version 7.1.0 of WorldEdit and 3.6.18 of AsyncWorldEdit Premium.

**Comment by therealatsuga** [comment]
Same....  can confirm. 

https://codeshare.io/5X1loz

**Comment by SBPrime** [comment]
Duplicate of #296 please comment there.
