### ISSUE TITLE
Problem with plugin see below

### ISSUE THREAD

**Issue by xTHEV0iDx** [SBPrime/AsyncWorldEdit#293]
You state on your plugin page that both the free version and the paid version are the same but I see a discrepancy in this, and I quote:

"Starting from the 1'st of January 2018 the AsyncWorldEdit Premium and the free versions are again one software. All the changes and features added to the premium are now available for everyone."

Then I see version 3.6.16 is the only free version and there is a 3.6.18 that is available.

You should consider updating your pages so they are more accurate. I have reported the resource so that this can get updated.

Cheers.

**Comment by SBPrime** [comment]
Read the description to the end:
"All the updates to the premium version will eventually be added to the free version (it might be days it might be weeks) after the premium release. First the changes will be available as source code. The JAR release for the free version might be released might not. It might skip some versions, it might be released the same day as the premium, it might be released after couple of weeks. "

Available: yes,
In the same form: no,
At the same time: no.
