### ISSUE TITLE
Entities are not copied

### ISSUE THREAD

**Issue by Mario359** [SBPrime/AsyncWorldEdit#297]
Hello,
When I use the _//copy_ or _//copy -e_ command with a selection that contains entities, such as sheeps, arrows, or armor stands, none of these entities appear after a //paste, only the blocks are pasted

I use: Paper 1.15.2, WorldEdit 7.1.0 and AsyncWorldEdit 3.6.16

**Comment by SBPrime** [comment]
You need to provide full server startup log, but from the looks of it you are using a mismatched version of WE and AWE.

**Comment by Mario359** [comment]
I tried several solutions, using WorldEdit 7.2.0, and even removing AsyncWorldEdit, but the bug still there so the problem doesn't come from this plugin but directly with WorldEdit
