### ISSUE TITLE
Low BPS

### ISSUE THREAD

**Issue by thanick99** [SBPrime/AsyncWorldEdit#301]
Hi, we are experiencing very low BPS when ever we exceed 3-4 players on the server. Can you help by telling us what to change in the config? The server has plenty of free RAM so that shouldnt be a problem, and TPS is 20 when it happens. 

[config.txt](https://github.com/SBPrime/AsyncWorldEdit/files/4463695/config.txt)
![17a796d19d6190b654802d561c01b4a0](https://user-images.githubusercontent.com/43637745/79029116-3bafb000-7b93-11ea-98e9-702aa05ab9a2.png)

**Comment by SBPrime** [comment]
Send spigot user name and full server startup log

**Comment by thanick99** [comment]
https://www.spigotmc.org/members/nexlemav.42880/

[latest.log](https://github.com/SBPrime/AsyncWorldEdit/files/4467900/latest.log)

**Comment by SBPrime** [comment]
Please set awe log level to debug, do a single block edit and send me the log.
Also please send the AWE config.

**Comment by SBPrime** [comment]
No response closing.
