### ISSUE TITLE
Update warning is telling to to get 3.6.20 but 3.6.19 is latest!

### ISSUE THREAD

**Issue by runelynx** [SBPrime/AsyncWorldEdit#305]
Please update the update-checker so it only warns us when something is actually available, thank you. 

![image](https://user-images.githubusercontent.com/5877481/79690650-10773180-8221-11ea-815a-30a17630f33f.png)

![image](https://user-images.githubusercontent.com/5877481/79690657-1ec54d80-8221-11ea-811c-903d02232588.png)

**Comment by SBPrime** [comment]
This is intentional, the plugin informs you about PREMIUM version update.

**Comment by ZandercraftGames** [comment]
#319 This really isnt the way to go if you are looking to get people to buy the premium version.
