### ISSUE TITLE
Error while during command

### ISSUE THREAD

**Issue by Cryper** [SBPrime/AsyncWorldEdit#306]
We try to use AsyncWE on our server, before we updatet to 1.15.2 it worked well, but now we only get this error :
Warning: Class scanner encountered an error while scanning class
Full Error:
[Error.txt](https://github.com/SBPrime/AsyncWorldEdit/files/4528835/Error.txt)

**Comment by SBPrime** [comment]
There is a plug-in that attaches to we pipeline. Set awe log level to debug mode and do 1block edit. I provide support on how to configure the server to premium users therefore you also need to provide spigot user name.

**Comment by Cryper** [comment]
My Name on Spigot is "Cryper96".
I activated debugmode on.  Now i got a diffrent error
[Error.txt](https://github.com/SBPrime/AsyncWorldEdit/files/4533029/Error.txt)

**Comment by SBPrime** [comment]
This is not the debug log ;), in config set debugLevel DEBUG.

**Comment by Cryper** [comment]
Ah ok, btw the url to the valid options is a dead end, isnt avaible anymore.
Debug on: Spamed over 42k lines
[Error.txt](https://github.com/SBPrime/AsyncWorldEdit/files/4533906/Error.txt)

**Comment by SBPrime** [comment]
I know it will spam alot of lines thats why I requested it. I need the top of the class scanner. It went in some place that it should not. Please send the log starting from the command. The one that you have send me it not good.

**Comment by Cryper** [comment]
Alright :) I copied almost every line.  I hope its enough information :) i didnt managed to delete all other lines
[error (2).txt](https://github.com/SBPrime/AsyncWorldEdit/files/4537579/error.2.txt)

**Comment by SBPrime** [comment]
Problem is caused by lands, the log is good enough to tell what was wrong although not to solve the problem :). To help you I need the log starting from the command.

**Comment by Cryper** [comment]
I'm not home at the moment. As soon i can i'll upload it. I can talk do the Lands Dev and report the issue if its helps

**Comment by SBPrime** [comment]
It would help if he used the AWE API and blacklisted their classes from class scanner.

**Comment by Cryper** [comment]
Alright, i'll redirect it to the Lands Dev

**Comment by SBPrime** [comment]
Will you provide the full server log?

**Comment by Cryper** [comment]
Jep. here is the full server log
[latest.log](https://github.com/SBPrime/AsyncWorldEdit/files/4571417/latest.log)

**Comment by SBPrime** [comment]
```me.angeschossen.lands.ZQcfIup.lSIbzNU.AVFyDzs.BuuupNF```

Add this class to AWE class scanner black list.
