### ISSUE TITLE
AsyncWorldEdit Wont function on Java 14

### ISSUE THREAD

**Issue by rmellis** [SBPrime/AsyncWorldEdit#307]
This resource works fine on Java 8 - 11 but when trying to use in OpenJDK14 it loads with no console errors but dosent take effect, all the commands work but the async is always off even when on
This happens on Windows Mac and Linux

**Comment by SBPrime** [comment]
Only java up to 11 is supported. When you use unsupported java you get an error on startup.

**Comment by rmellis** [comment]
The report was more just me letting you know.. java 14 is allready being used by many people for Minecraft Servers and the numbers are only geting bigger.. i mean FAWE is allready working on java 14 so why not make this work?

**Comment by SBPrime** [comment]
fawe is a fork of we my plugin attaches to we using reflection with was changed in 12+

**Comment by rmellis** [comment]
okay I know its not a big issue and I know what fawe is, I just wasn't sure if you were even aware which is why I posted this in the first place, I'm sorry if I seem like I'm being funny about it, I think this is a great resource and it is a great solution for many people.
We all appreciate your hard work.
Thank You!
