### ISSUE TITLE
Unable to Delegate Extent Action

### ISSUE THREAD

**Issue by Exillium313** [SBPrime/AsyncWorldEdit#309]
I get this randomaly when I copy or cut something, https://pastebin.com/9AxhAM7K

Any help would be greatly appreciated! This is on a paper server using ASWE v 3.6.20 ( Free )

**Comment by SBPrime** [comment]
Error is caused by error in server configuration, not related to AWE plugin. Server configuration support is available for premium users.

**Comment by Exillium313** [comment]
Purchased plugin and im awaiting verification to download premium version, now can you please help me?

SpigotName: PirateKalypso

**Comment by Exillium313** [comment]
@SBPrime Can you provide support now? I purchased the premium version.

**Comment by SBPrime** [comment]
Long story short: install blockshub, disable WE integration in coreprotect. Configure AWE and blockshub to use coreprotect.

**Comment by Exillium313** [comment]
`  #Blocks hub plugin options  
  blocksHub:
    log:
        #Enable block change logging
        isEnabled: true
        #Enable block change logging for Direct Chunk API
        isDcEnabled: false
    #The block access control
    access:
        #Enable blocks access control
        isEnabled: false
        #Enable blocks access control for Direct Chunk API
        isDcEnabled: false
        #Allow NULL player to place blocks (used by some plugins)
        allowNull: false
        #Allow unknown player to place blocks
        allowUnknown: true
        #Allow console player to place blocks
        allowConsole: true
        #Allow offline player to place blocks
        allowOffline: false`

I dont see an option to configure AWE to use CoreProtect, am I missing something? Any changes i should make to this section? Ive installed Blocks hub, and disabled WE for CoreProtect.

**Comment by SBPrime** [comment]
Sorry typo I meant AWE to use blockshub, it looks like you have it setup.
