### ISSUE TITLE
Error when executing command "//set stone" on 1.15.2

### ISSUE THREAD

**Issue by bloggy** [SBPrime/AsyncWorldEdit#310]
Error:
https://pastebin.com/161W8hqN

Versions:
This server is running Tuinity version git-Tuinity-"9616aa9" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Loading AsyncWorldEdit v3.6.20
Enabling WorldEdit v7.1.0;8e55131

**Comment by bloggy** [comment]
I think this is caused by CoreProtect, not sure if it is repairable in AWE

**Comment by TNTUP** [comment]
No issues on Paper 1.15.2, probably something with Tuinity? Can't test this fork to confirm as I'm on J8^^

**Comment by SBPrime** [comment]
Does not look like a problem with AWE try with WE only.

**Comment by ZEROOblivious** [comment]
https://pastebin.com/hqZyWySi

I'm having the same issue.

**Comment by SBPrime** [comment]
@ZEROOblivious this is a different problem. Please create a new issue.

**Comment by SBPrime** [comment]
Not an issue of AWE.
