### ISSUE TITLE
Disable message with tp compass

### ISSUE THREAD

**Issue by dylanjcq** [SBPrime/AsyncWorldEdit#311]
Hello,

I have to look a little and quibble at the config but I have not found.
When the players use the compass, left click (tp) and right click (pass through the walls), messages in the chat are displayed, I would like to deactivate these messages only for the compass but I can't find how.

**Here are the messages:**

> 
> Running navigationWand in full async mode.
> Job [0] navigationWand - placing blocks
> Blocks processed: 0
> Job [0] navigationWand - done

**Comment by SBPrime** [comment]
In AWE config disable async for navigationWand.

**Comment by PaDo90** [comment]
> In AWE config disable async for navigationWand.

don't work for me.
How i can add this? Like this?

`  disabledOperations: {}
  - navigationWand
  #  - undo
  #  - redo
  #  - fillXZ
  #  - fillXY`
