### ISSUE TITLE
Gravity brush moving blocks it shouldn't

### ISSUE THREAD

**Issue by MegaNarwhal** [SBPrime/AsyncWorldEdit#312]
Without AWE, the gravity brush stops moving blocks down when there is a non-air block beneath them. With AWE, blocks continue to be moved down even when they are directly above a solid block. Running WorldEdit 7.1.0 and AWE 3.7.1. This occurs with no other plugins except a permissions plugin and Vault.

Here are examples with and without AWE running:
https://imgur.com/a/yq16mc5

**Comment by MegaNarwhal** [comment]
This still occurs in AWE 3.7.2 with default config.

**Comment by SBPrime** [comment]
Fixed in 37.3
