### ISSUE TITLE
Illegal reflective access by org.primesoft.asyncworldedit.utils.Reflection

### ISSUE THREAD

**Issue by ice-fly** [SBPrime/AsyncWorldEdit#315]
**Just a heads up:**

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.primesoft.asyncworldedit.utils.Reflection (file:/C:/Users/Username/Documents/Minecraft/plugins/AsyncWorldEdit-3.6.20.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.primesoft.asyncworldedit.utils.Reflection
```
`git-Paper-304 (MC: 1.15.2)`
Thank you for your hard work!

**Comment by SBPrime** [comment]
You did not specify the java version and plugin version.

**Comment by ice-fly** [comment]
![image](https://user-images.githubusercontent.com/11548922/82526406-f2dc0700-9b01-11ea-8b52-a7481432227a.png)
![image](https://user-images.githubusercontent.com/11548922/82526444-08513100-9b02-11ea-905f-342501024c3c.png)

**Comment by ice-fly** [comment]
Found it after scanning through all the console crap spit out by AsyncWorldEdit v3.6.20

**Comment by SBPrime** [comment]
Version that you are using is working with java up to 11. Java 11 simply complains about potential incompatibility. To get support for java 12+ you need AWE 3.7+.

**Comment by Magicrafter13** [comment]
> Version that you are using is working with java up to 11. Java 11 simply complains about potential incompatibility. To get support for java 12+ you need AWE 3.7+.

I get the same warning with Java 13, and AWE 3.7.5.

**Comment by ice-fly** [comment]
![image](https://user-images.githubusercontent.com/11548922/87276977-67eb0d80-c4af-11ea-9f90-cb6140940c3c.png)
![image](https://user-images.githubusercontent.com/11548922/87276924-4ee25c80-c4af-11ea-897f-1bad2cb81ce5.png)
Yep...

**Comment by SBPrime** [comment]
@ice-fly send me a log, not a screenshot. The screen contains some info, although it does not show all.

**Comment by SBPrime** [comment]
No reply.
