### ISSUE TITLE
AsynchWorldEdit ignores worldedit.setnbt

### ISSUE THREAD

**Issue by FreedomForeverMC** [SBPrime/AsyncWorldEdit#320]
So, i wanted to deny people from setting nbt tags with //paste so i removed their permission for worldedit.setnbt but it just gets ignored. i tried without AWE and it doesnt paste NBT data but with AWE it just ignores the permission and sets NBT data with //paste

**Comment by SBPrime** [comment]
Fixed in 3.7.3
