### ISSUE TITLE
Tile is null, asynchronous access?

### ISSUE THREAD

**Issue by SamB440** [SBPrime/AsyncWorldEdit#322]
Got this error when doing a //paste:
https://pastebin.com/VsAsypgj

Environment:
openjdk version "14.0.1" 2020-04-14 (Java 14)
git-Paper-334 (MC: 1.15.2)
AsyncWorldEdit 3.7.2
WorldEdit 7.1.0;8e55131
Plugins:
![image](https://user-images.githubusercontent.com/11319274/84058313-f8b26300-a9b0-11ea-973e-ecb81f0539da.png)

**Comment by SBPrime** [comment]
Please provide the server startup log.

**Comment by SamB440** [comment]
https://pastebin.com/dPnzvBe1

**Comment by SBPrime** [comment]
You are using core protect for loging worldedit operations. Please follow the installation instruction of the plugin to fix the problem. Full support for setting up the server is available for premium users.
