### ISSUE TITLE
//setbiome doesn't work (1.16.1 paper)

### ISSUE THREAD

**Issue by jaylawl** [SBPrime/AsyncWorldEdit#325]
https://gyazo.com/e2e265a8ce0335fcb0147a97c873d257 stacktrace
https://gyazo.com/4c2ecdeb08ed52bfce517df2bea5fc71 ingame feedback

plugins:
- AWE 3.7.3
- WorldEdit 7.2.0-beta-01+0eb9ac7
- MEINKRAFT (non-interfering lightweight admin tools library)

running:
- git-Paper-18 (1.16.1)

additional info:
//setbiome *does* work when using regular worldedit

**Comment by Aurelien30000** [comment]
Confirmed ^^

**Comment by SBPrime** [comment]
Fixed in 3.7.4
