### ISSUE TITLE
[1.16.1] Crash WE + AWE + Plotsquared

### ISSUE THREAD

**Issue by minemalia** [SBPrime/AsyncWorldEdit#329]
Hey,

When I start up my 1.16.1 paperspigot server, the server crashes with the following error: https://pastebin.com/v53dvaez
When I remove the Asyncworldedit plugin, the server starts up as usual.

AsyncWorldEdit-3.7.3 (free-version)
Plotsquared 5.12.1-Premium
Worldedit worldedit-bukkit-7.2.0-beta-01
Paper 1.16.1, build 45.

It would be nice if you could fix this.

Thanks in advance!

**Comment by SBPrime** [comment]
This bug was fixed 3.7.4. Free version will most likely get it next week (depending how much free time I'll have).
