### ISSUE TITLE
Async causes issues with Multiverse core on 1.16.1

### ISSUE THREAD

**Issue by e101stella** [SBPrime/AsyncWorldEdit#330]
Basically as title, without async in multiverse core loads perfectly fine, with it this error comes up presumably because of some class modifications.
![image](https://user-images.githubusercontent.com/37426292/86709059-e9304380-c05c-11ea-9852-74ff06f59a29.png)

Edit: To be a little more precise, this is running AWE v3.7.3 with Multiverse Core v 4.1.1 snapshot and WE 7.2.0 Beta 1

**Comment by SBPrime** [comment]
This was fixed in 3.7.4.
