### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by xSepticSidx** [SBPrime/AsyncWorldEdit#333]
HI.
I'm on 1.16.1 - paper.
With AsyncWorldEdit 3.7.5.

I'm seeing the following in my startup log.
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] Modify class com.sk89q.worldedit.LocalSession
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] ****************************
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * CLASS INJECTION FAILED!! *
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] ****************************
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * AsyncWorldEdit won't work properly.
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] *
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * >>>> Please make sure that you are using a supported version of world edit <<<< 
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] *
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] *
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * Exception: java.lang.IllegalStateException
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * Error message: Field 'history:Ljava/util/LinkedList;' not found.
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * Stack: 
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.utils.SimpleValidator.validate(SimpleValidator.java:70)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.visitors.BaseFieldAccessorVisitor.validate(BaseFieldAccessorVisitor.java:76)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modifyClasses(InjectorCore.java:373)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modifyClasses(InjectorCore.java:340)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.injectClasses(InjectorCore.java:246)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:186)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:89)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.inject(AsyncWorldEditBukkit.java:232)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:94)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * java.lang.Class.forName0(Native Method)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * java.lang.Class.forName(Class.java:348)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] * java.lang.Thread.run(Thread.java:748)
18.07 16:00:23 [Server] INFO [AsyncWorldEdit] ****************************
18.07 16:00:33 [Server] INFO [AsyncWorldEdit] Unable to initialize injector.
18.07 16:00:33 [Server] INFO [AsyncWorldEdit] ERROR: Unable to enable the injector.

**Comment by SBPrime** [comment]
What version of WorldEdit are you using.

**Comment by xSepticSidx** [comment]
7.2.0-snapshot+5183-5f9f105

**Comment by SBPrime** [comment]
Only official releases form dev bukkit are supported. You need to use 7.2.0-beta-02
