### ISSUE TITLE
Disable dumb messages,

### ISSUE THREAD

**Issue by Yhteys** [SBPrime/AsyncWorldEdit#335]
Anyway to disable those extra messages, they're useless imo?
> I only want to see the "Undid 1 available edits" message.

[https://cdn.discordapp.com/attachments/705852108171116636/735464021607841843/unknown.png](url)

**Comment by Yhteys** [comment]
Bump

**Comment by SBPrime** [comment]
There was no answer because the screen that you provided was empty.

**Comment by MitchTalmadge** [comment]
I'm not related to this issue but here is the image OP wanted to post.

![image](https://user-images.githubusercontent.com/8848080/91259352-90f7f280-e72b-11ea-9c1b-2906acf853cb.png)

**Comment by SBPrime** [comment]
Go to config and set awe talkative to false.
