### ISSUE TITLE
No WorldEdit 7.2.0 Beta 3 Compatability

### ISSUE THREAD

**Issue by TwoPointInfinity** [SBPrime/AsyncWorldEdit#339]
WorldEdit 7.2.0 Beta 1 and 2 are no longer available for download through dev bukkit. Without compatibility to beta 3 the plugin is unusable to users unable to find beta 2 download. 

Edit:
Beta 2 Download: https://builds.enginehub.org/job/worldedit/14969

**Comment by jerzean** [comment]
here is the error it thows to further help this issue

also fun fact here is the download for Worldedit 7.2.0-beta2
[https://builds.enginehub.org/job/worldedit/14969](url)

`15.08 05:01:49 [Server] Server thread/WARN Loaded class org.primesoft.asyncworldedit.injector.injected.util.eventbus.IDispatchableEventBus from AsyncWorldEdit v3.7.5 which is not a depend, softdepend or loadbefore of this plugin.
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.math.BlockVector2
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.math.BlockVector3
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.math.Vector2
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.math.Vector3
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.world.block.BlockStateHolder
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.world.block.BaseBlock
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.world.block.BlockState
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.entity.BaseEntity
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.util.Location
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.world.biome.BiomeType
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.world.weather.WeatherType
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.EditSession
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.extent.AbstractDelegateExtent
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.function.operation.Operations
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.extension.platform.PlayerProxy
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.util.collection.LocatedBlockList
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.extent.reorder.MultiStageReorder
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.extent.reorder.ChunkBatchingExtent
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.regions.AbstractRegion
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.regions.EllipsoidRegion
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.regions.ConvexPolyhedralRegion
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.regions.TransformRegion
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.regions.RegionIntersection
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.regions.NullRegion
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.regions.Polygonal2DRegion
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.regions.CylinderRegion
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.regions.CuboidRegion
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.command.SnapshotUtilCommands
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.command.ScriptingCommands
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.command.SchematicCommands
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.command.RegionCommands
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.command.UtilityCommandsRegistration
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.bukkit.BukkitEntity
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.command.RegionCommandsRegistration
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.function.mask.AbstractExtentMask
15.08 05:01:49 [Server] Server thread/INFO Modify class com.sk89q.worldedit.LocalSession
15.08 05:01:49 [Server] Server thread/INFO ****************************
15.08 05:01:49 [Server] Server thread/INFO * CLASS INJECTION FAILED!! *
15.08 05:01:49 [Server] Server thread/INFO ****************************
15.08 05:01:49 [Server] Server thread/INFO * AsyncWorldEdit won't work properly.
15.08 05:01:49 [Server] Server thread/INFO *
15.08 05:01:49 [Server] Server thread/INFO * >>>> Please make sure that you are using a supported version of world edit <<<< 
15.08 05:01:49 [Server] Server thread/INFO *
15.08 05:01:49 [Server] Server thread/INFO *
15.08 05:01:49 [Server] Server thread/INFO * Exception: java.lang.IllegalStateException
15.08 05:01:49 [Server] Server thread/INFO * Error message: Field 'history:Ljava/util/LinkedList;' not found.
15.08 05:01:49 [Server] Server thread/INFO * Stack: 
15.08 05:01:49 [Server] Server thread/INFO * org.primesoft.asyncworldedit.injector.utils.SimpleValidator.validate(SimpleValidator.java:70)
15.08 05:01:49 [Server] Server thread/INFO * org.primesoft.asyncworldedit.injector.core.visitors.BaseFieldAccessorVisitor.validate(BaseFieldAccessorVisitor.java:76)
15.08 05:01:49 [Server] Server thread/INFO * org.primesoft.asyncworldedit.injector.core.InjectorCore.modifyClasses(InjectorCore.java:373)
15.08 05:01:49 [Server] Server thread/INFO * org.primesoft.asyncworldedit.injector.core.InjectorCore.modifyClasses(InjectorCore.java:340)
15.08 05:01:49 [Server] Server thread/INFO * org.primesoft.asyncworldedit.injector.core.InjectorCore.injectClasses(InjectorCore.java:246)
15.08 05:01:49 [Server] Server thread/INFO * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:186)
15.08 05:01:49 [Server] Server thread/INFO * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:89)
15.08 05:01:49 [Server] Server thread/INFO * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.inject(AsyncWorldEditBukkit.java:232)
15.08 05:01:49 [Server] Server thread/INFO * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:94)
15.08 05:01:49 [Server] Server thread/INFO * java.lang.Class.forName0(Native Method)
15.08 05:01:49 [Server] Server thread/INFO * java.lang.Class.forName(Class.java:348)
15.08 05:01:49 [Server] Server thread/INFO * org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64)
15.08 05:01:49 [Server] Server thread/INFO * org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
15.08 05:01:49 [Server] Server thread/INFO * org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
15.08 05:01:49 [Server] Server thread/INFO * org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301)
15.08 05:01:49 [Server] Server thread/INFO * org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:382)
15.08 05:01:49 [Server] Server thread/INFO * net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:186)
15.08 05:01:49 [Server] Server thread/INFO * net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810)
15.08 05:01:49 [Server] Server thread/INFO * net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
15.08 05:01:49 [Server] Server thread/INFO * java.lang.Thread.run(Thread.java:748)
15.08 05:01:49 [Server] Server thread/INFO ****************************
15.08 05:01:59 [Server] Server thread/INFO Unable to initialize injector.
15.08 05:01:59 [Server] Server thread/INFO ERROR: Unable to enable the injector.`

**Comment by TwoPointInfinity** [comment]
Thank you @jerzean I wasnt able to grab a log from the other plugins in my server making a mess of my logs, and thank you for finding the beta 2 build. I wasnt able to find it through the world edit dev bukkit page, since its removed and only showed beta 3. it's not as easy to find so cheers.

**Comment by willies952002** [comment]
The [premium version](https://www.spigotmc.org/resources/9661) of the plugin already has support for `7.2.0-beta-03`. 
The source in this repo is, from what I'm seeing, at least one version behind.
