### ISSUE TITLE
AsyncWorldEdit isn't compatible with worldedit beta 4

### ISSUE THREAD

**Issue by AccioAce** [SBPrime/AsyncWorldEdit#341]
Hello SB,
This is Ace from spigot. It seems like the latest asyncworldedit isn't working properly with worldedit beta 4. It seems like when I ever copy signs and paste the signs all the words disappears and leaves the signs empty.

version screenshot: https://gyazo.com/8fee5e02b9c67d138dd7709d28eda473

**Comment by SBPrime** [comment]
done in 3.8.0
