### ISSUE TITLE
//sphere

### ISSUE THREAD

**Issue by marzenie** [SBPrime/AsyncWorldEdit#344]
typing // sphere doesn't show a message about the blocks placed, nor does it show the api
(I think it is almost like that for all // commands)

**Comment by SBPrime** [comment]
Send the console log.

**Comment by marzenie** [comment]
ok sorry i forgot about it will send tomorrow

**Comment by marzenie** [comment]
logs 
[latest.log](https://github.com/SBPrime/AsyncWorldEdit/files/5321433/latest.log)

**Comment by marzenie** [comment]
normally in e.g. //set I have a chat message and on the bar at the top, in the case of //sphere it still gets asynchronous but there are no progess messages

**Comment by marzenie** [comment]
I also have suggestions to be able to turn off async in options if it is less than X blocks

**Comment by SBPrime** [comment]
Sorry for not replying, I was unable to reproduce. Sphere works correctly.
