### ISSUE TITLE
AsyncWorldEdit does not set block metadata

### ISSUE THREAD

**Issue by Speeder323** [SBPrime/AsyncWorldEdit#346]
![image](https://user-images.githubusercontent.com/61844671/95013155-a7547080-063e-11eb-8641-a80920d7bd21.png)
When I //set iron_bars a simple area with AWE installed, it did not set their metadata.
Removing AWE let WorldEdit set that metadata.

**Comment by SBPrime** [comment]
send the server log for operation and server startup, also try the same operation with physics freeze set to off

**Comment by Speeder323** [comment]
well it works. not sure why physics freeze was responsible for this issue

**Comment by Speeder323** [comment]
![image](https://user-images.githubusercontent.com/61844671/95013913-b7228380-0643-11eb-9ceb-92e82073398a.png)
What about rotation/delay of the repeaters though?

**Comment by Speeder323** [comment]
(left: original, right: copied)
Is the version of worldedit to blame?

**Comment by SBPrime** [comment]
Error was not caused by AWE.
