### ISSUE TITLE
You have too many jobs queued, operation canceled

### ISSUE THREAD

**Issue by x1p** [SBPrime/AsyncWorldEdit#349]
On 1 of my servers, a player got this message. Normal players, like him, have no WE permissions.
I noticed that many default players had a undo directory some of which contained undo files (0 bytes)
The only divergent thing was the presence of an old `AsyncWorldEdit-ActionBarAPI.jar` plugin.

I disabled AWE + AWEBB for now as it was not really necessary on this particular server.

Still strange isn't it? Why would AWE make undo jobs if players haven't executed anything related to WE?

I don't expect you have an explanation for this. If you can't do anything with this issue, feel free to close it after reading it.
BTW FYI: AWEBB is not functioning entirely properly on latest WE

Paper 1.16.3
AWE 3.8.0
WE 7.2.0 beta 5

**Comment by SBPrime** [comment]
AWEBB? What do you mean?
Regarding the undo dirs are there empty? or contain empty files?

**Comment by x1p** [comment]
With AWEBB I mean https://www.spigotmc.org/resources/asyncworldedit-boss-bar.76600/

There were recent files in the undo folder of it with strange file extensions.

**Comment by SBPrime** [comment]
I investigated the problem, an if users had no access to WE commands then there must be a 3'rd party plugin that uses WE and forces AWE to kick in. If you like I can investigate it further although I'll need more information about 3'rd party plugins and some logs/commands that lead to this message.

**Comment by x1p** [comment]
I raised the number of jobs to 2 (just to make sure). I haven't noticed any recent issues regarding this.
