### ISSUE TITLE
Can place blocks over limit

### ISSUE THREAD

**Issue by Nastroszona** [SBPrime/AsyncWorldEdit#356]
![image](https://user-images.githubusercontent.com/68341231/100572044-d866bf80-32d4-11eb-9875-e497f1992472.png)

I have problem with placing blocks over limit - my players have no limit in awe, I set limits on 3 groups and it show on chat, but it doesn't work...

Server on paper, 1.16

**Comment by SBPrime** [comment]
The queue limit works correctly (tested using a small limit), the message might be misleading because it also adds the selected region size to the queued blocks count.
