### ISSUE TITLE
Java 16 support

### ISSUE THREAD

**Issue by Dymeth** [SBPrime/AsyncWorldEdit#377]
As you know, Minecraft 1.17 will only work in Java 16 and above. Seems like AsyncWorldEdit is having a problems?

https://pastebin.com/raw/LG6NanaF

**Comment by pseudoforceyt** [comment]
getting the same error
[aweerror.txt](https://github.com/SBPrime/AsyncWorldEdit/files/6501830/aweerror.txt)

**Comment by James-Cotterill** [comment]
Getting the same issue. Will this support be added to both versions?

**Comment by SBPrime** [comment]
Java 16 is a bi*** in terms of reflection and my plugin...

At this moment I can suggest only one solution:
Add ```--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED``` to the command line.

I'm still trying to find a proper workaround in the code, but it might not be possible without a full rewrite of the way AWE is hooking into WE classes.

**Comment by James-Cotterill** [comment]
Thank you for the quick response and I'm sorry for the frustration this must be causing. Are these lines to be added to the Linux console ? I know you are probably unsure but do you have a rough estimate on how long this may take as we rely a lot on this great plugin? :)

**Comment by SBPrime** [comment]
@James-Cotterill Yes there is a "hacky" way to work around it (already posted it ;) ), simple add: 
```--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED```

I tested it and the plugin worked correctly. If it does not work, send me the console log.

More read:
https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m/41265267#41265267

In terms of ATE: it depends, if I will need to rewrite the hooking mechanics it might take a 1.5 month+. If I manage to find an alternative solution then I should have it by the end of the  next week.

**Comment by Postremus** [comment]
@SBPrime 
Lombok had similar problems on jdk 16, they found a way around adding add-opens on jdk 16.
Issue: https://github.com/projectlombok/lombok/issues/2681
Commit: https://github.com/projectlombok/lombok/commit/9806e5cca4b449159ad0509dafde81951b8a8523

**Comment by OpticFusion1** [comment]
I got around this by using ClassGraph personally, not sure how useful it'll be for this project though

**Comment by SBPrime** [comment]
Currently I'm considering migrating from `java.lang.reflect.Method;` to `java.lang.invoke.MethodHandle;` and java.lang.invoke.MethodHandles.privateLookupIn(...)`. It looks promising, although it requires some other hacks.

@Postremus I did not find that solution, only one from powermock. Will try it later perhaps it will be a valid solution (and a quick win ;) )

@OpticFusion1 I assume that you are talking about this: `https://github.com/classgraph/classgraph`, if that is the case how exactly did it help? In my case I need to access (and invoke) some protected methods from `ClassLoader`:


```
final class ClassInjectorBukkit implements IClassInjector {
    ...
    public ClassInjectorBukkit() {
            ...
            m_miDefineClass = SecureClassLoader.class.getDeclaredMethod("defineClass",
                    String.class, byte[].class, int.class, int.class, CodeSource.class);
            m_miDefineClass.setAccessible(true);
            ...
    }

    ...
    private Class<?> injectClass(
            final ClassLoader cl,
            final String name,
            final byte[] bin,
            final int off,
            final int len,
            final CodeSource codeSource) throws ClassFormatError {

        try {
            return (Class<?>) m_miDefineClass.invoke(cl, name, bin, off, len, codeSource);
        } catch (Exception ex) {
            throw (ClassFormatError) (new ClassFormatError("Unable to inject class.").initCause(ex));
        }
    } 
    ...
}
```
https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEditInjector/src/main/java/org/primesoft/asyncworldedit/injector/ClassInjectorBukkit.java#L105-L107

https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEditInjector/src/main/java/org/primesoft/asyncworldedit/injector/ClassInjectorBukkit.java#L124-L137
 
And another one here:
```
public abstract class Loader extends ClassLoader implements ILibraryLoader {
...
    static {
        s_findLoadedClass = Reflection.findMethod(ClassLoader.class,
                "findLoadedClass", "Unable to find findLoadedClass method on ClassLoader", String.class);
        ...
    }

...
    @Override
    protected synchronized Class&lt;?&gt; loadClass(String name, boolean resolve) throws ClassNotFoundException {
        Class<?> cls = findLoadedClass(m_classLoader, name);
        ...
    }

    private static Class<?> findLoadedClass(ClassLoader classLoader, String name) {
        if (s_findLoadedClass == null) {
            return null;
        }
        return Reflection.invoke(classLoader, Class.class, s_findLoadedClass,
                "Unable to invoke findLoadedClass", name);
    }
...
}
```

https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/main/java-templates/org/primesoft/asyncworldedit/Loader.java#L106-L107

https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/main/java-templates/org/primesoft/asyncworldedit/Loader.java#L246-L253

https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/main/java-templates/org/primesoft/asyncworldedit/Loader.java#L171-L174

**Comment by James-Cotterill** [comment]
> @James-Cotterill Yes there is a "hacky" way to work around it (already posted it ;) ), simple add:
> `--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED`
> 
> I tested it and the plugin worked correctly. If it does not work, send me the console log.
> 
> More read:
> https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m/41265267#41265267
> 
> In terms of ATE: it depends, if I will need to rewrite the hooking mechanics it might take a 1.5 month+. If I manage to find an alternative solution then I should have it by the end of the next week.

Thank you so much for the support and quick reply.

We have added the tags suggested and the plugin is now in green and attempting to load which is great.

Unfortunately it however does like the the latest version of WorldEdit - worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar (the only one we could get working on Java 16) does not support it. Please see attached console log. Not sure if you have any other suggestions at this point or if anyone can recommend a version of worldedit that works both on Java16 and AWE with the suggested work around. 

Console: https://pastebin.com/qY0NCRqS

**Comment by SBPrime** [comment]
@James-Cotterill someone on the forum suggested it might be because of spigot update, it can also be an i compatibility with we. I had a full success running 3weeks old WE on Spigot from around the same time and java 16.

Never the less there is a separate issue for injector failure please folloup there and not mix topics ;)

**Comment by SBPrime** [comment]
@Postremus The lombook hack works :P thx for suggesting it.

Closing the ticket, java 16 compatibility will be added in net release.
