### ISSUE TITLE
Items not removing after //undo until a rejoin

### ISSUE THREAD

**Issue by James-Cotterill** [SBPrime/AsyncWorldEdit#379]
Firstly a MASSIVE thank you for the latest update and turnaround on sorting the Java16 issue really appreciate it! 

Everything seems to be working great but one weird bug.

When doing //undo it says the undo was complete however the blocks are still there.

However if you leave the world and come back or reconnect the items have then updated and vanished.

Any idea on what this could be?

Thanks

**Comment by SBPrime** [comment]
Its already on my radar, there might already be an issue on github (or at least someone mentioned it on spigot).

**Comment by James-Cotterill** [comment]
No worries thank you:

Here is the console error which will hopefully help:

[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] -----------------------------------------------------------------------
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] Warning: Class scanner encountered an error while scanning class
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] Exception: java.lang.reflect.InaccessibleObjectException, Unable to make field private static final long java.util.ArrayList.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @1f85a44d
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.scanner.ClassScanner.unpack(ClassScanner.java:313)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.scanner.ClassScanner.scan(ClassScanner.java:190)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:192)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethod(Helpers.java:91)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java)
[6:27 PM]
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.EditSession.internalFlushSession(EditSession.java:938)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.EditSession.setReorderMode(EditSession.java:375)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.LocalSession.prepareEditingExtents(LocalSession.java:1061)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1054)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.primesoft.asyncworldedit.worldedit.WrappedLocalSession.createEditSession(WrappedLocalSession.java:240)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:251)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.Optional.map(Optional.java:260)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:250)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.Optional.flatMap(Optional.java:289)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[6:27 PM]
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:647)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:408)
[6:27 PM]
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.enginehub.piston.CommandManager.execute(CommandManager.java:157)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:496)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.lang.reflect.Method.invoke(Method.java:567)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:375)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55)
[6:27 PM]
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.lang.Thread.run(Thread.java:831)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] Class: class java.util.ArrayList
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] Object: []
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] Send this message to the author of the plugin!
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] https://github.com/SBPrime/AsyncWorldEdit/issues
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] -----------------------------------------------------------------------
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] -----------------------------------------------------------------------
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] Warning: Class scanner encountered an error while scanning class
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] Exception: java.lang.reflect.InaccessibleObjectException, Unable to make field transient java.lang.Object[] java.util.ArrayDeque.elements accessible: module java.base does not "opens java.util" to unnamed module @1f85a44d
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
[Sat, 22. May 2021 17:26:56 UTC INFO] [AsyncWorldEdit] java.base/java.lang.reflect.Field.setAccessible(Field.java:171)

**Comment by James-Cotterill** [comment]
> Its already on my radar, there might already be an issue on github (or at least someone mentioned it on spigot).

Hi,

Sorry to chase but just wondered if you had any luck with this issue?

We will be using WE a lot moving bases to a new 1.17 world shortly so would be very useful.

Understand there are higher priorities but just thought I'd ask.

Thanks again!

**Comment by SBPrime** [comment]
Class scanner error fixed. When testing the ghosting did not appear on 1.17.

I'll leave it open for now. Please validate.

**Comment by James-Cotterill** [comment]
> Class scanner error fixed. When testing the ghosting did not appear on 1.17.
> 
> I'll leave it open for now. Please validate.

Afternoon,

Thank you for the update.

We have just updated and unfortunately we are still experiencing the same issues.

The error being produced does however seem different - https://pastebin.com/ir9v6fSQ

I am aware I am still running MC 1.16.5 while waiting for Paper to release 1.17 so not sure if this is related.

Thanks

**Comment by mrfloris** [comment]
I am using latest premium from spigotmc and paper 17 build 53, and i still get this. Is there a test build i can dl somewhere?

to @op, relogging is not needed btw, you can /spawn or /home and then /back, and it's updated.

**Comment by SBPrime** [comment]
Should be fixed in 3.9.1, did you try that version? Can you share the edit that you did?

**Comment by mrfloris** [comment]
Just upgraded from spigot, i see a new build is out, thank you - i've scheduled a test for tomorrow morning.
