### ISSUE TITLE
Exception: java.lang.reflect.InaccessibleObjectException, Unable to make field transient java.lang.Object[] java.util.ArrayDeque.elements accessible: module java.base does not "opens java.util" to unnamed module @3506ebdf

### ISSUE THREAD

**Issue by Towelie** [SBPrime/AsyncWorldEdit#382]
Full error: https://pastebin.com/AigCcJ9M
Noticed this error in the console.
AsyncWorldEdit (3.8.4)
WorldEdit (7.3.0-SNAPSHOT+5775-ec2fb07)
This server is running Paper version git-Paper-720 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by UCCGaming** [comment]
Same error running on WorldEdit 7.2.5

**Comment by SBPrime** [comment]
The error ir related to raflection not WorldEdit. I asume that you are using java 16?

**Comment by DrBennelly** [comment]
Same error too, running Java 16, WorldEdit 7.2.5+57d5ac9, AsyncWorldEdit version 3.8.4 and Paper version git-Paper-745 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT).
Error : https://pastebin.com/1DCz2yg2

**Comment by UCCMinecraft** [comment]
> The error ir related to raflection not WorldEdit. I asume that you are using java 16?

Yes, we updated to Java 16 in prep for 1.17.

**Comment by SBPrime** [comment]
Should be fixed in latest release.
