### ISSUE TITLE
Set command causes stacktrace. (Java16)

### ISSUE THREAD

**Issue by NeverGrowUp** [SBPrime/AsyncWorldEdit#389]
Using AWE 3.9.0, WE 7.2.5, Tuinity 1.16.5-234, Java16

Using the //set command causes stacktrace No:2 below. (although still functions fine). Using //replace works fine.
Adding `--illegal-access=permit` flag suppresses the stack
> 23:07:46 [INFO]: _adnap_ issued server command: //set air
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.primesoft.asyncworldedit.asyncinjector.scanner.ClassScanner to field java.util.ArrayDeque.elements
WARNING: Please consider reporting this to the maintainers of org.primesoft.asyncworldedit.asyncinjector.scanner.ClassScanner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

2. Stacktrace without java flag.
https://pastebin.com/8ayyQMNg

**Comment by myriadblades** [comment]
same problem for me, hope they find a fix.

**Comment by SBPrime** [comment]
Fixed in 3.9.1
