### ISSUE TITLE
Smooth not working in async mode

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/AsyncWorldEdit#39]

**Comment by Matmorcat** [comment]
Same problem. Here's the error.
https://gist.github.com/Matmorcat/1eb82d3e319acb8dc45fa71983646d1f

**Comment by SBPrime** [comment]
Your error has nothing to do with this issue. You are using a unsupported WorldEdit version, please start a new issue.

**Comment by snwflake** [comment]
Is there a way to omit async mode when using smooth?
