### ISSUE TITLE
Error with `//fixlava` and `//fixwater`

### ISSUE THREAD

**Issue by Zoro-6191** [SBPrime/AsyncWorldEdit#396]
![image](https://user-images.githubusercontent.com/52291201/123759814-e10c8c00-d8dd-11eb-8178-839a6901717d.png)

Console error on `//fixlava` and `//fixwater`

https://mcpaste.io/6c057e7dab696ff5

Paper 1.17#53

**Comment by SBPrime** [comment]
Please try on 3.9.1, should be fixed.

**Comment by Zoro-6191** [comment]
Works, no errors
thanks
