### ISSUE TITLE
List of modified blocks after schematic paste

### ISSUE THREAD

**Issue by Gnacik** [SBPrime/AsyncWorldEdit#406]
Hello. Its not a issue, but ask for help.
Im using AWE API to paste schematic, and i need list of modified blocks in world after job is done, can you point me to solution?

**Comment by SBPrime** [comment]
Hey, if you only would like to monitor the changed blocks by API call it will require hooking into blockshub api (you will need a block logger). Is your plugin using actual player ids or fakes to run the job?

**Comment by Gnacik** [comment]
cannot find any examples how to use block logger on internet. im usign real player. my code: https://pastebin.com/XssCBMv6

**Comment by Gnacik** [comment]
ok, nevermind. I found how to use EditSessionEvent and setExtent in we and it without problems works also with awe.
