### ISSUE TITLE
Error while regenerating chunk.

### ISSUE THREAD

**Issue by ErythroCraft** [SBPrime/AsyncWorldEdit#412]
Hi

After //paste a structure and using //regen 
Chunks will not reganerate.

Watch out the console log.

[2021-09-29-2.log](https://github.com/SBPrime/AsyncWorldEdit/files/7254624/2021-09-29-2.log)

**Comment by SBPrime** [comment]
this is not caused by awe, you are using a version of we that is not compatible with your server

**Comment by ErythroCraft** [comment]
I do not understand.
Do you mean we=WorldEdit ?

**Comment by ErythroCraft** [comment]
If yes, what version is compatible with 
(MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

**Comment by ErythroCraft** [comment]
@SBPrime
So, now I installed the letest release of WorldEdit (stable) and AWEPremium (latest).
But there is the same ERROR.

[latest.log](https://github.com/SBPrime/AsyncWorldEdit/files/7257619/latest.log)

**Comment by ErythroCraft** [comment]
And I've seen in your description ...
1. download and install WorldEdit 7.1.0

But this version is still running on spigot/bukkit v.1.15.2
I can not install WorldEdit 7.1.0 on a Spigot 1.17.1 server.

The stable version of WorldEdit is on a Spigot 1.17.1 server is WorldEdit 7.2.6

**Comment by ErythroCraft** [comment]
Now I added a bug report on WordEdits GitHub
