### ISSUE TITLE
Support for WorldEdit 7.2.x and/or 7.3

### ISSUE THREAD

**Issue by ErythroCraft** [SBPrime/AsyncWorldEdit#419]
Hi

Can you give an update to worldedit 7.2.x and 7.3

WorldEdit 7.2.x (1.13.2 - 1.18.1) - stable
https://builds.enginehub.org/job/worldedit/19089

WorldEdit 7.3.0 (1.13.2 - 1.18.1) - experimental
https://builds.enginehub.org/job/worldedit/19156

**updates of WorldEdit below**

**Comment by willies952002** [comment]
Any word on the progress of this/#417?

**Comment by ErythroCraft** [comment]
@willies952002 here are all updates and infos why AsynchWorldEdit is not working on 1.18.1 servers.
An update for AsynchWorldEdit to 1.18.1 is required, because MC1.18 has not the Log4J-2 update.


Lates stable version of WorldEdit 7.2.x on GitHub is https://github.com/EngineHub/WorldEdit/tree/version/7.2.x

Lates stable version of WorldEdit 7.2.x on DevBukkit is https://dev.bukkit.org/projects/worldedit/files/3559523
Lates stable version of WorldEdit 7.2.x on Spigot is https://dev.bukkit.org/projects/worldedit/files/3559523


Lates stable version of WorldEdit 7.2.9 on EngineHub is https://builds.enginehub.org/job/worldedit/19521
Lates stable version of WorldEdit 7.3.0 on EngineHub is https://builds.enginehub.org/job/worldedit/19235

Default is Java17 because the Log4J was updated to Log4J-2
Java17: https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html
Log4J-2: https://logging.apache.org/log4j/2.x/

**Comment by SBPrime** [comment]
Sorry, but I don't get it. The currently available version 3.9.3, free and premium that was released on the 4'th of December:
* is compatible with the released version of WorldEdit (7.2.8)
* it works fine on Spigot 1.18.1spigot
* I do not use Log4J (granted I have an import for the API but the classes are provided by spigot so if you updated you are good to go)
* It works fine on java 17

Is there anything else?

**Comment by ErythroCraft** [comment]
Is ok.

I'm using FAWE since yesterday. 
It's working with all my installed plugins, paper and mods on my server.
The payments of my private accounts will be deleted next month.

Have fun and a long life.
