### ISSUE TITLE
Toggleable verbose output of 'talking' state.

### ISSUE THREAD

**Issue by mibby** [SBPrime/AsyncWorldEdit#42]
A command to toggle talking state for specific players so individuals can decide if they want the information or not, instead of hard locking enabled or disabled? Maybe to go even further, customize what talks back?

https://github.com/SBPrime/AsyncWorldEdit/issues/41#issuecomment-56265148

**Comment by SBPrime** [comment]
Done in premium.

**Comment by mibby** [comment]
3.5+ years later. :D

**Comment by SBPrime** [comment]
This was added in premium a long time ago I was going over all isues after publishing the premium source code.
