### ISSUE TITLE
Is AsyncWorldedit-Forge using Log4j

### ISSUE THREAD

**Issue by Oklinq** [SBPrime/AsyncWorldEdit#421]
Is the mod safe to use or is the log4j exploid not fixed yet?

Thank you for your anwser

**Comment by SBPrime** [comment]
Hey the plugin is compiled against "a version" of log4j, but it does not drag-in any version of log4j to the class path of the server. It is the responsibility of the server software (spigot) to provide actual log4j classes on the class path. Therefore if you followed the instructions on how to secure your server, AWE will use the updated version of log4j.
