### ISSUE TITLE
Is there any way to install 1.18.1 version as a Forge mod? 

### ISSUE THREAD

**Issue by Oklinq** [SBPrime/AsyncWorldEdit#422]
I cant figure it out :(

Thank you

**Comment by SBPrime** [comment]
Sorry forge is not supported since cauldron died.
Forge only mode is also not supported. Perhaps in the future...

**Comment by TheFantasticLoki** [comment]
well shit. Is there any chance we can get a forge specific port? I am trying to paste a MASSIVE 500 radius schematic into my modded world and can't use mcedit and normal worldedit just ain't cutting it
