### ISSUE TITLE
Original Plugin?

### ISSUE THREAD

**Issue by FrostBlade5** [SBPrime/AsyncWorldEdit#427]
I am confused.
So there is worldedit, then we have async worldedit, and we also have fast async worldedit.
Now im lost.
Which is the original plugin and which plugin? And most important which has the best performance?

I am speaking about this:
https://github.com/SBPrime/AsyncWorldEdit/
https://github.com/IntellectualSites/FastAsyncWorldEdit
https://dev.bukkit.org/projects/worldedit/files

Thank you.

**Comment by lorenzop** [comment]
AsyncWorldEdit works with the original WorldEdit plugin, improving the performance and helping to avoid some lag. WorldEdit is still needed to make this work.

FastAsyncWorldEdit is a fork of WorldEdit, meaning it replaces the original WorldEdit and does things a bit different.

I'd recommend you try them both, one at a time, see what you like better. I personally like the original WorldEdit paired with AsyncWorldEdit.

**Comment by SBPrime** [comment]
Adding on top what was already said, AsyncWorldEdit aims for server stability not for speed.
