### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xen1290** [SBPrime/AsyncWorldEdit#62]
Hi @SBPrime , With 2.0.2 I have this error on console:
http://pastebin.com/c31utHxT
WordEdit 6.0.0 from here: http://dev.bukkit.org/bukkit-plugins/worldedit/files/60-world-edit-6-0/

**Comment by vediis** [comment]
@Xen1290 Hey this is a LONNGGG shot, but do you happen to still have the file Prism-2.0.3-Cauldron-MC1.7-b16?
