### ISSUE TITLE
I have errors in the console

### ISSUE THREAD

**Issue by Christian4945** [SBPrime/AsyncWorldEdit#65]
I'm running 1.8 spigot I put in the Worldedit 6.0 in and the latest version of async but still get an error not sure why so here is a picture of the error
![untitled](https://cloud.githubusercontent.com/assets/10374822/5598782/9c8bf79a-9281-11e4-9ae6-dd7929e37be8.png) its the only error not sure what is the matter help is much needed thank you!

**Comment by Postremus** [comment]
you also need the asyncworldeditinjector, that you can find inside the
downloaded zip, on your server.

2015-01-02 20:17 GMT+01:00 Christian4945 <notifications@github.com>:

**Comment by SBPrime** [comment]
That's correct you need to put the injector and the core plugin. Please read the installation manual on the plugin page.

Closing issue: works for me

**Comment by Christian4945** [comment]
I was never told in the instruction that i need to install it too but ok thxs
