### ISSUE TITLE
users can WorldEdit on plots that aren't theirs

### ISSUE THREAD

**Issue by coolty** [SBPrime/AsyncWorldEdit#66]
Hi,

I was told here to open an issue with you since apparently you are modifying PlotMe classes and causing users to be able to use the //replace tool anywhere, even on plots that aren't theirs and in the roads.

From the dev of PlotMe:
"Tell them I sent you to them because they are modifying PlotMe Classes and it is most likely causing these issues. "

**Comment by coolty** [comment]
correction: use of the //repl tool, not //replace. for example: //repl 0 then the user (non admin/op) with worldedit permissions can then right click on a block that isn't on his plot, or in the road, and it will disappear.

**Comment by SBPrime** [comment]
First of all I do not modify any of the PlotMe classes only the WorldEdit classes. I do only one thing that is PlotMe related, that is update the mask before user calls a command.

Secondly it would help if you provided the versions of AWE/WE/PlotMe.

**Comment by coolty** [comment]
Hi,

Here is a startup log of my server with the versions. 

http://pastebin.com/raw.php?i=gAbJXZQ3

**Comment by SBPrime** [comment]
Why did you close it before letting me test it :P?

**Comment by coolty** [comment]
I did not close the issue, it was closed by the dev. After it was closed he decided that I should open an issue here.

**Comment by SBPrime** [comment]
Ye my bad I misread, at first glance it looked like you closed the AWE issue. Testing it at the moment.

**Comment by SBPrime** [comment]
Ok tested it, and can't reproduce it. With or without AWE (using latest AWE, PlotME and WE). WE, AWE, PlotMe are set to default configuration.

**Perms:**

    worldedit.*
    awe.*
    plotme.*
    -plotme.admin.buildnywhere

I also tested this using OP, PlotMeFix Disabled, and no go. I was able to WE outside the plot only when I had buildanywhere or had weanywhere on. Could you try to provide more details?

**Comment by coolty** [comment]
I can't really provide more details unless you want something specific.

I noticed in your permissions listed that you are giving yourself plotme.* but negating 
"plotme.admin.buildnywhere". This is incorrect as you should only give yourself plotme.use (not to mention that the permission was spelled incorrectly, also the permission plotme.admin.weanywhere should be also negated if you are going to go that route.

**Comment by SBPrime** [comment]
That was a typo I had the perms set correctly and I wanted to test all PlotMe commands. When I set the perms to the one that you provided nothing changed. I was unable to edit anything out of my plot.

More details: a step by step how you are able to reproduce it, can you reproduce it when you remove AWE?

**Comment by coolty** [comment]
Hm. I can confirm that this issue still happens when AWE and AWE injector is removed.

You can close this issue....
