### ISSUE TITLE
Bad handling of jobs.

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/AsyncWorldEdit#69]
"Now I am finding a new issue where I'm generating a creative flat and am setting grids for plots by copy/pasting a 3x3 section. I'm not seeing the message for block queue being unlocked, and when I go to paste it tells me that i have too many operations queued and cancelling current operation, then it starts working on the next line."

http://i.imgur.com/RQdmQUw.jpg

**Comment by SBPrime** [comment]
This was no caused by block queue limit not allowing to add "job done" event.

Could you send me the exact output what you do exactly and what AWE answers. Maby the log will helo? I have no idea what happened based on the screen.

**Comment by Nubebuster** [comment]
Also it's nearly impossible to detect when a job is finished using the api.

**Comment by Intensearmadillo** [comment]
I agree, there needs to be some way for developers to know when a job is finished, how long until it will be finished, and the current BPS... the same information the player is able to contain when using worldedit.

**Comment by SBPrime** [comment]
@Nubebuster : There is a way, use the BLocksHub.jobAdded/Removes and Job.stateChanged listeners.

@Intensearmadillo : Please put all the API comments/requests in #29.

**Comment by SBPrime** [comment]
Not confirmet, unable to reproduce
