### ISSUE TITLE
Concurrent Modification Error

### ISSUE THREAD

**Issue by MylesIsCool** [SBPrime/AsyncWorldEdit#73]
Hey there,

I'm getting a concurrent modification error - Code I'm using:
```
for (BlockPlacerEntry e : AsyncWorldEditMain.getInstance().getBlockPlacer().getPlayerEvents(PlayerEntry.UNKNOWN).getQueue()) {
														if (e.getJobId() == jobID) {
															b++;
														}
													}
```
This is being used to count the number of blocks left, it is ran via the bukkit scheduler and is causing the following error:
```
java.util.ConcurrentModificationException
        at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:632) ~[?:1.7.0_71]
        at com.koletar.jj.mineresetlite.Mine$10$1.run(Mine.java:678) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
```
I wouldn't assume the list should be locked at this point?

**Comment by SBPrime** [comment]
Yes please look at the BlockPlacer class how it should be locked.

https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/org/primesoft/asyncworldedit/blockPlacer/BlockPlacer.java
