### ISSUE TITLE
Error while changing a lot of blocks

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [SBPrime/AsyncWorldEdit#75]
Think I got this error while changing a lot of blocks: http://pastebin.com/EMQ9fPsz

**Comment by SBPrime** [comment]
Could you provide the command that caused the problem?

**Comment by TheOnlyRealTGS** [comment]
Might be //undo or it was //replace x x not sure

**Comment by SBPrime** [comment]
I was hoping that you could provide the whole pattern that you have used for replace ;)

**Comment by TheOnlyRealTGS** [comment]
Well, in replace's case it was //replace barrier 5 //replace 5:2 barrier //replace barrier 5:2 or something

**Comment by SBPrime** [comment]
According to the error message ("Error message: org.primesoft.asyncworldedit.utils.SessionCanceled") the job was canceled using AWE command. Please verify if this is the case.

**Comment by TheOnlyRealTGS** [comment]
Ah, it was maybe caused by doing //undo while it was undoing?

**Comment by SBPrime** [comment]
Undo cancels current job and starts undooing the current last operation.

**Comment by TheOnlyRealTGS** [comment]
I know, but is there supposed to be an error?

**Comment by SBPrime** [comment]
Well currently its normal. I might change it in the next release. I need to figure a better way to handle this.

**Comment by TheOnlyRealTGS** [comment]
Okay
