### ISSUE TITLE
I cant detect what job is done.

### ISSUE THREAD

**Issue by Nubebuster** [SBPrime/AsyncWorldEdit#82]
I need to paste schematics asyncly, but I cant figure out how to detect when they're done pasting.
Here's my code:
http://pastebin.com/rRaCSpim

How do I identify what job is done?

"AsyncEditSession.getPlayer() " returns an "\<unknown\>" player.

Thanks for your help.

**Comment by SBPrime** [comment]
Use BlocksPlacer.PerformAsAsyncJob + add a job added/removed listener to BlocksPlacer.

**Comment by Nubebuster** [comment]
BlocksPlacer.PerformAsAsyncJob ues the following parameters: Editsession, player, name, FuncParameterEx.

how do i get a fake player? and what is the FuncParameterEx?

**Comment by SBPrime** [comment]
Check those 3 classes:
[FuncParamEx.java](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/org/primesoft/asyncworldedit/utils/FuncParamEx.java)
[PlayerManager.java](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/org/primesoft/asyncworldedit/PlayerManager.java)
[PlayerEntry.java](https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/org/primesoft/asyncworldedit/PlayerEntry.java)

**Comment by Nubebuster** [comment]
I've already checked out the FuncParamEx class but I dont get it

**Comment by Nubebuster** [comment]
That discussion didnt fix my problem, the UUID doesnt change and I have tried to make it work so many times that I gave up back then. Now my server is full enough that creating so many games freezes the server too often.

**Comment by SBPrime** [comment]
You have 2 options to identify a job. Either create a custom job name or create a custom player wrapper. To detect that a job is created you need to listen for  public void BlockPlacer.addListener(IBlockPlacerListener listener). 

The FuncParamEx is a simple class that allows you to wrap some operations and past them as a parameter for other function. You should do it like this:

    new FuncParamEx<Integer, CancelabeEditSession, MaxChangedBlocksException>() {
       public Integer Execute(CancelabeEditSession param) throws MaxChangedBlocksException
       {
           //Do some operations on the param.
       }
    };

**Comment by Nubebuster** [comment]
Easiest would be a custom job name but the name is renamed to "place" after it's first state change.

**Comment by Nubebuster** [comment]
I am sorry but this is just so lame. Could you please just spoonfeed me with code with an annotation where to run my code that needs to be run after the pasting.

**Comment by SBPrime** [comment]
Ok please tell me how do you want it to work exactly? Is this invoked by console/internal? Invoked by player? should this run multiple instances at a time? If it's player based should the blocks count as a player placed and queued on user queue?

**Comment by Nubebuster** [comment]
whenever the system creates a new game, a schematic needs to be pasted at "origin". After the pasting is done I need to cycle through the blocks to detect beacons, those will be the player spawns once the game starts. After cycling through the blocks the game can start. Multiple games must be created at the same time.

**Comment by Nubebuster** [comment]
I decided to parse schematics myself, so this is not necessary anymore.

**Comment by SBPrime** [comment]
Sorry for not answering sooner, but I had to fix the errors first + had some other work on my hands. Never the less I'm going to write a tutorial how to use the AWE API here on github. So if your still interested check it.
