### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by TWSSYesterday** [SBPrime/AsyncWorldEdit#85]
With release 2.1.5 https://github.com/SBPrime/AsyncWorldEdit/releases/tag/2.1.5 Do I have to use the plotme version there?

**Comment by SBPrime** [comment]
No PlotMe is optional you don't need it.If you don't use PlotMe install only the AsyncWorldEdit.jar and AsyncWorldEditInjector.jar. If you are using PlotMe in addition to the previous 2 you need to use the additional AsyncWorldEdit-PlotMe*.jar thats appropriate for your version.
