### ISSUE TITLE
AWE craftscript crash

### ISSUE THREAD

**Issue by Pocketkid2** [SBPrime/AsyncWorldEdit#88]
http://pastebin.com/AhrjdPvQ

This happens when I try to run a craft script with world edit, specifically this one: https://github.com/echurchill/WorldEdit_City/blob/master/fab.js

**Comment by Pocketkid2** [comment]
It does generate the city, but it doesn't show any messages.

**Comment by SBPrime** [comment]
Please send me the exact version of awe and we

**Comment by SBPrime** [comment]
The script is not updated compatible with the latest WE version.
