### ISSUE TITLE
Regenerating terrain causes errors

### ISSUE THREAD

**Issue by unon1100** [SBPrime/AsyncWorldEdit#89]
Using //regen seems to edit the world Asynchronously, causing many IllegalStateExceptions. 

[23:59:08 INFO]: [AsyncWorldEdit] Error performing safe operation for plotme3 cx:622 cy:111 Loaded: true, inUse: false. Error: java.lang.IllegalStateException: Asynchronous entity world add!

**Comment by SBPrime** [comment]
@unon1100 
@EvilOlaf

I added "special" logging of the reported error. Its going to be pushed to the next version. If you encounter the error once more please reopen.

**Comment by EvilOlaf** [comment]
I am unable to reopen this due to lack of permission but I think writing will do too ;)
Thanks for inquiring.

**Comment by SBPrime** [comment]
Ok then give me a shout if you have anything to report. 

Regarding the error: this error is semi normal situation. AWE only tells you that it was unable to perform this operation in optimistic (fast) mode and it needs to fall back to queued (slow) mode for "get" operations. I implemented a test function that checks if the "safe" mode is valid but apparently sometimes my check function gives false positive.

**Comment by mibby** [comment]
@SBPrime Any ETA on the new build?
