### ISSUE TITLE
AWE Crash

### ISSUE THREAD

**Issue by Pocketkid2** [SBPrime/AsyncWorldEdit#91]
Async World Edit 2.1.5

http://pastebin.com/HDTRgWRU

**Comment by SBPrime** [comment]
Send the versions of: Spigot, WorldEdit
+ Any additional information you could provide (server startup log?)

**Comment by Pocketkid2** [comment]
http://pastebin.com/LKTJvLc5

**Comment by SBPrime** [comment]
This looks like WorldEdit problem did you try to reproduce it without AWE installed?

**Comment by SBPrime** [comment]
Not confirmed, unable to reproduce, works for me.

**Comment by Pocketkid2** [comment]
Yes, this must have just been a dumb error that is currently fixed
