### ISSUE TITLE
Language file not changing

### ISSUE THREAD

**Issue by niels1189** [SBPrime/AsyncWorldEdit#92]
Considerable amount of messages are being sent out by the plugin and is a bit annoying on bigger servers with more people talking in chat.

Tried removing as many messages as possible but was unable to remove quite a few.
Language file wasn't updating, tried multiple things but didn't work.

**Comment by SBPrime** [comment]
Please send your config file, language file and AWE version.

**Comment by niels1189** [comment]
Version: 2.1.5
Config: http://pastebin.com/YgKiqZGQ
Language file: http://pastebin.com/0mXF2C02

Note that I changed about 3 lines in the language file to experiment if things changed. They didn't.
I also noticed that the talkative & progress-chat weren't changing when I updated them.
They still displayed all their messages. It's also unclear what talkative does exactly.

**Comment by niels1189** [comment]
Problem found:

Config 1st line, onceawe needs to be changed to awe:
That resolves the issue.
Perhaps add a comment to tell people to change that in the auto generated config.

**Comment by SBPrime** [comment]
This is strange, according to the default config (https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/config.yml) everything is ok. It looks like your config was changed, please verify how this happened.

**Comment by niels1189** [comment]
Not sure, I let it generate by default and that's what came out. Changed values and started using it.
Haven't had a problem since I changed it to awe.

**Comment by SBPrime** [comment]
It wont work if the configuration root is not set to awe, if this happens it uses the defaults. Well if you can't tell me more I'm gonna close the issue. Did you manage to resolve the language file issue?

**Comment by SBPrime** [comment]
Do you have anything to add to this issue? If not I'm gonna close this as "cant reproduce/works for me".

**Comment by niels1189** [comment]
Resolved once I changed the first line to aws

**Comment by niels1189** [comment]
awe, instead of onceawe

**Comment by SBPrime** [comment]
Ok but did it generate correctly after a clean reset or not?

**Comment by niels1189** [comment]
yes it did. I think the fault was with me copying an online config and perhaps typing in once when doing CTRL+F to find something related to 'once'.
