### ISSUE TITLE
Support for pause AWE jobs

### ISSUE THREAD

**Issue by EvilOlaf** [SBPrime/AsyncWorldEdit#93]
Hey,

as many others I ran often fully automatic backup scripts. They pause common tasks like Dynmap rendering, WorldBorder filling, auto-save and such things and unpauses them after the backup has been completed.

Processing bigger jobs with AWE made me thinking if there is a way to pause AWE jobs.

**Comment by SBPrime** [comment]
Currently there is no way to pause the job, you can only cancel it. Unfortunately I have no plans on adding extra features in near future, I lost most of my motivation to work on the plugin. I'll look into this when I get back to development.

**Comment by SBPrime** [comment]
Currently there is no way to pause the job, you can only cancel it. Unfortunately I have no plans on adding extra features in near future, I lost most of my motivation to work on the plugin. I'll look into this when I get back to development.

**Comment by EvilOlaf** [comment]
Sad to hear.
Hope you find your way back in future :)

**Comment by EvilOlaf** [comment]
Nice.
