### ISSUE TITLE
Reload and version permissions are backwards

### ISSUE THREAD

**Issue by Bobcat00** [SBPrime/AsyncWorldEdit#96]
It appears these two permissions are switched:

public enum Permission {

    /**
     * Allows the use of the Reload command
     */
    RELOAD_CONFIG("admin.version"),

    /**
     * Informs the user on login if the plugin is updated or not
     */
    ANNOUNCE_VERSION("admin.reload"),

**Comment by SBPrime** [comment]
This is not backwards its by dessign. I Have a "backwards" notation for all nodes. I assumed that the first node is the group then command and finally command variant.
