### ISSUE TITLE
Error with Cauldron

### ISSUE THREAD

**Issue by Time6628** [SBPrime/AsyncWorldEdit#98]
I tried using AWE on my cauldron server and I got this error:
http://pastebin.com/NSFuZRZA

WorldEdit-Bukkit-6.0
worldedit-forge-mc1.7.10-6.0-beta-01.jar
AWE 2.2.0
AWEPlotme 2.2.0
AWEInjector 2.2.0
cauldron-1.7.10-1.1381.06.221
Send help! xD
-Time

**Comment by SBPrime** [comment]
Caused by: java.lang.NoSuchFieldError: plotworldedit
            at org.primesoft.asyncworldedit.plotme.PlotMeFix_013g.setMask(PlotMeFix_013g.java:84) ~[?:?]

You need PlotMeFix only if you have installed PlotMe. According to the provided stack you either do not have any PlotMe or you have installed a wrong version of the PlotMeFix. One more thing please update AWE to 2.2.1 there is a bug in 2.2.0

**Comment by Time6628** [comment]
Fixed it, thanks :smile:
