### ISSUE TITLE
Not Notify When No Update

### ISSUE THREAD

**Issue by roastnewt** [SBPrime/AsyncWorldEdit#99]
Is there any way to add a config option or a permission or something, so that AWE doesn't notify you when there's NOT an update?  I appreciate being notified when there is an update, but I don't need to be told "You have the latest version of the plugin" every time I log in :)

**Comment by SBPrime** [comment]
Try changing the message in the language file (english.yml)

**Comment by SBPrime** [comment]
Duplicate #133
